### ISSUE TITLE
合并13b模型时报错

### ISSUE THREAD

**Issue by ChrisXULC** [ymcui/Chinese-LLaMA-Alpaca#152]
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /root/anaconda3/envs/lmflow did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.4/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 114
/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /root/anaconda3/envs/lmflow/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so...
Loading checkpoint shards: 100%|██████████████████████████████████████████████| 3/3 [00:18<00:00,  6.17s/it]
Extended vocabulary size: 49954
Traceback (most recent call last):
  File "/root/LMFlow/cn_llama/packages/./Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py", line 148, in <module>
    new_state_dict[new_k] = unpermute(v)
  File "/root/LMFlow/cn_llama/packages/./Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py", line 101, in unpermute
    w.view(n_heads, 2, dim // n_heads // 2, dim).transpose(1, 2).reshape(dim, dim)
RuntimeError: shape '[32, 2, 64, 4096]' is invalid for input of size 26214400

**Comment by ChrisXULC** [comment]
fix
