### ISSUE TITLE
text-generation-webui部署时报错Can't find config.json at 'loras\['chinese-alpaca-lora-13b']'

### ISSUE THREAD

**Issue by qingying6** [ymcui/Chinese-LLaMA-Alpaca#184]
**loras里本来就没有config.json文件怎么会报这个错呢？？**
(llama.cpp-master) d:\tools\text-generation-webui>python server.py --model llama_13b_hf --lora chinese-alpaca-lora-13b --gpu-memory 6
Gradio HTTP request redirected to localhost :)
Loading llama_13b_hf...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 3/3 [03:36<00:00, 72.13s/it]
Loaded the model in 218.80 seconds.
Applying the following LoRAs to llama_13b_hf: chinese-alpaca-lora-13b
---------['chinese-alpaca-lora-13b']-----------
Traceback (most recent call last):
  File "D:\python3\llama.cpp-master\lib\site-packages\peft\utils\config.py", line 99, in from_pretrained
    config_file = hf_hub_download(pretrained_model_name_or_path, CONFIG_NAME)
  File "D:\python3\llama.cpp-master\lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\python3\llama.cpp-master\lib\site-packages\huggingface_hub\utils\_validators.py", line 157, in validate_repo_id
    raise HFValidationError(f"Repo id must be a string, not {type(repo_id)}: '{repo_id}'.")
huggingface_hub.utils._validators.HFValidationError: Repo id must be a string, not <class 'pathlib.WindowsPath'>: 'loras\['chinese-alpaca-lora-13b']'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\tools\text-generation-webui\server.py", line 919, in <module>
    add_lora_to_model([shared.args.lora])
  File "d:\tools\text-generation-webui\modules\LoRA.py", line 44, in add_lora_to_model
    shared.model = PeftModel.from_pretrained(shared.model, Path(f"{shared.args.lora_dir}/{lora_names}"), **params)
  File "D:\python3\llama.cpp-master\lib\site-packages\peft\peft_model.py", line 135, in from_pretrained
    config = PEFT_TYPE_TO_CONFIG_MAPPING[PeftConfig.from_pretrained(model_id).peft_type].from_pretrained(model_id)
  File "D:\python3\llama.cpp-master\lib\site-packages\peft\utils\config.py", line 101, in from_pretrained
    raise ValueError(f"Can't find config.json at '{pretrained_model_name_or_path}'")
ValueError: Can't find config.json at 'loras\['chinese-alpaca-lora-13b']'

**Comment by lucoo01** [comment]
同问

**Comment by iMountTai** [comment]
peft版本是多少？

**Comment by lucoo01** [comment]
后面我合并模型后再次运行就可以了
