### ISSUE TITLE
python inference script 无法直接加载模型

### ISSUE THREAD

**Issue by DavidHoApoidea** [ymcui/Chinese-LLaMA-Alpaca#194]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 问前必查项目

- [ ] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [ ] LLaMA
- [x] Alpaca

问题类型：
- [ ] 下载问题
- [ ] 模型转换和合并问题
- [x] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [ ] 效果问题
- [ ] 其他问题

### 运行截图或log
CUDA_VISIBLE_DEVICES=0 python scripts/inference_hf.py \
>     --base_model ziqingyang/chinese-alpaca-lora-7b \
>     --with_prompt \
>     --interactive
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/opt/conda/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/ziqingyang/chinese-alpaca-lora-7b/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1166, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1507, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 269, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-64425e8a-74f9c1872deb645b2c2a6d26)

Entry Not Found for url: https://huggingface.co/ziqingyang/chinese-alpaca-lora-7b/resolve/main/config.json.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/inference_hf.py", line 56, in <module>
    base_model = LlamaForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2269, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 547, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/hub.py", line 454, in cached_file
    raise EnvironmentError(
OSError: ziqingyang/chinese-alpaca-lora-7b does not appear to have a file named config.json. Checkout 'https://huggingface.co/ziqingyang/chinese-alpaca-lora-7b/main' for available files.

**Comment by ymcui** [comment]
你仔细看看文档：https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/使用Transformers推理
`--base_model`指定的是**合并后的模型**，不是LORA文件。
