### ISSUE TITLE
inference_hf.py推理报错RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by kingdomad** [ymcui/Chinese-LLaMA-Alpaca#206]
### 问前必查项目

- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [x] LLaMA
- [ ] Alpaca

问题类型：
- [ ] 下载问题
- [ ] 模型转换和合并问题
- [x] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [ ] 效果问题
- [ ] 其他问题

### 详细描述问题

scripts/inference_hf.py推理报错如下：

Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.65s/it]
Vocab of the base model: 49954
Vocab of the tokenizer: 49954
Start inference with interactive mode.
Input:你好
Traceback (most recent call last):
  File "/home/dev/git_projects/Chinese-LLaMA-Alpaca/scripts/inference_hf.py", line 107, in <module>
    generation_output = model.generate(
  File "/home/dev/anaconda3/envs/deeplearning/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dev/anaconda3/envs/deeplearning/lib/python3.9/site-packages/transformers/generation/utils.py", line 1559, in generate
    return self.sample(
  File "/home/dev/anaconda3/envs/deeplearning/lib/python3.9/site-packages/transformers/generation/utils.py", line 2634, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

这个脚本中CUDA_VISIBLE_DEVICES好像没用？
通过修改脚本device = torch.device('cpu')指定cpu也是一样报错。

**Comment by kingdomad** [comment]
经过排查发现是模型文件在拷贝过程中md5发生了变化导致。

**Comment by zhanshijinwat** [comment]
是否开启了8bit模式，我是开了8bit模型进行推理就会出现这个问题，保持半精度模式吧
