### ISSUE TITLE
Running server.py reports an error:KeyError: 'serialized_input'

### ISSUE THREAD

**Issue by LeoYYG** [ymcui/Chinese-LLaMA-Alpaca#258]
python server.py --model llama-7b-hf --lora chinese-alpaca-lora-7b --cpu

Running server.py reports an error:

INFO:Gradio HTTP request redirected to localhost :)
bin /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
INFO:Loading llama-7b-hf...
Loading checkpoint shards: 100%
INFO:Loaded the model in 14.44 seconds.
INFO:Applying the following LoRAs to llama-7b-hf: chinese-alpaca-lora-7b
Traceback (most recent call last):
  File "server.py", line 885, in <module>
    create_interface()
  File "server.py", line 803, in create_interface
    extensions_module.create_extensions_block()
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/gradio_client/serializing.py", line 40, in input_api_info
    return (api_info["serialized_input"][0], api_info["serialized_input"][1])
KeyError: 'serialized_input'

**Comment by Mr-nnng** [comment]
我也碰到了同样的问题，通过执行pip install --upgrade gradio，将gradio升级到3.28.3问题解决了
