### ISSUE TITLE
增量训练LLaMa词表下载出错

### ISSUE THREAD

**Issue by yangxuan14nlp** [ymcui/Chinese-LLaMA-Alpaca#278]
### 详细描述问题
Chinese-LLaMA-Alpaca# python ./scripts/merge_tokenizers.py   --llama_tokenizer_dir tokenizer.model
Traceback (most recent call last):
  File "/root/miniconda3/envs/doccano/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/root/miniconda3/envs/doccano/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/tokenizer.model/resolve/main/tokenizer.model

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/doccano/lib/python3.9/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/root/miniconda3/envs/doccano/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/doccano/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1134, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/root/miniconda3/envs/doccano/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/doccano/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1475, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/root/miniconda3/envs/doccano/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6459f1ff-0dfcae8351450eeb195d02fc)

Repository Not Found for url: https://huggingface.co/tokenizer.model/resolve/main/tokenizer.model.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/new_data/xyh/git_/Chinese-LLaMA-Alpaca/./scripts/merge_tokenizers.py", line 16, in <module>
    llama_tokenizer = LlamaTokenizer.from_pretrained(llama_tokenizer_dir)
  File "/root/miniconda3/envs/doccano/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1770, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/root/miniconda3/envs/doccano/lib/python3.9/site-packages/transformers/utils/hub.py", line 424, in cached_file
    raise EnvironmentError(
OSError: tokenizer.model is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/tokenizer.model/resolve/main/tokenizer.model

### 必查项目

- [ ] 哪个模型的问题：LLaMA **（只保留你要问的）**
- [ ] 问题类型：**（只保留你要问的）**
  - 下载问题

**Comment by iMountTai** [comment]
还请仔细阅读[准备工作：词表扩充](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C%E8%AF%8D%E8%A1%A8%E6%89%A9%E5%85%85)llama_tokenizer_dir并没在你执行程序的当前文件夹下
