### ISSUE TITLE
inference_hf.py發生錯誤

### ISSUE THREAD

**Issue by CRGBS** [ymcui/Chinese-LLaMA-Alpaca#326]
### 详细描述问题
CNAPL=合併後資料夾

執行以下cmd發生錯誤
```
python "J:\GPTAI\script\inference_hf.py" --base_model J:\GPTAI\llama-13b-hf --lora_model J:\GPTAI\CNAPL --with_prompt --interactive
pause
```

由於一開始提示找不到adapter_config文件
我就將ChineseAlpacaPlusLora13b內的adapter_config複製至CNAPL

之後執行即出現下列錯誤

### 运行截图或日志

```
J:\GPTAI>python "J:\GPTAI\script\inference_hf.py" --base_model J:\GPTAI\llama-13b-hf --lora_model J:\GPTAI\CNAPL --with_prompt --interactive
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████| 41/41 [04:49<00:00,  7.06s/it]
Vocab of the base model: 32000
Vocab of the tokenizer: 49954
Resize model embeddings to fit tokenizer
loading peft model
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\peft\peft_model.py", line 373, in load_adapter
    filename = hf_hub_download(model_id, WEIGHTS_NAME, subfolder=kwargs.get("subfolder", None))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\utils\_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'J:\GPTAI\CNAPL'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "J:\GPTAI\script\inference_hf.py", line 73, in <module>
    model = PeftModel.from_pretrained(base_model, args.lora_model,torch_dtype=load_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\peft\peft_model.py", line 181, in from_pretrained
    model.load_adapter(model_id, adapter_name, **kwargs)
 
File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\peft\peft_model.py", line 375, in load_adapter
    raise ValueError(
ValueError: Can't find weights for J:\GPTAI\CNAPL in J:\GPTAI\CNAPL or in the Hugging Face Hub. Please check that the file adapter_model.bin is present at J:\GPTAI\CNAPL.

J:\GPTAI>pause
```
### 補充
資料夾底下檔案
```
j:\GPTAI\Alpacafin
j:\GPTAI\ChineseAlpacaPlusLora13b
j:\GPTAI\ChineseLlamaPlusLora13b
j:\GPTAI\CNAPL
j:\GPTAI\LLaMA Convert to full hf formate.cmd
j:\GPTAI\LLaMA Convert to hf formate.cmd
j:\GPTAI\llama-13b-hf
j:\GPTAI\LORA MIX.cmd
j:\GPTAI\Readme.txt
j:\GPTAI\script
j:\GPTAI\start.cmd
j:\GPTAI\test.py
j:\GPTAI\Alpacafin\consolidated.00.pth
j:\GPTAI\Alpacafin\consolidated.01.pth
j:\GPTAI\Alpacafin\params.json
j:\GPTAI\Alpacafin\special_tokens_map.json
j:\GPTAI\Alpacafin\tokenizer.model
j:\GPTAI\Alpacafin\tokenizer_config.json
j:\GPTAI\ChineseAlpacaPlusLora13b\adapter_config.json
j:\GPTAI\ChineseAlpacaPlusLora13b\adapter_model.bin
j:\GPTAI\ChineseAlpacaPlusLora13b\special_tokens_map.json
j:\GPTAI\ChineseAlpacaPlusLora13b\tokenizer.model
j:\GPTAI\ChineseAlpacaPlusLora13b\tokenizer_config.json
j:\GPTAI\ChineseAlpacaPlusLora13b\YOU_MUST_ALSO_DOWNLOAD_LLAMA_PLUS_13B.md
j:\GPTAI\ChineseLlamaPlusLora13b\adapter_config.json
j:\GPTAI\ChineseLlamaPlusLora13b\adapter_model.bin
j:\GPTAI\ChineseLlamaPlusLora13b\special_tokens_map.json
j:\GPTAI\ChineseLlamaPlusLora13b\tokenizer.model
j:\GPTAI\ChineseLlamaPlusLora13b\tokenizer_config.json
j:\GPTAI\CNAPL\adapter_config.json
j:\GPTAI\CNAPL\config.json
j:\GPTAI\CNAPL\generation_config.json
j:\GPTAI\CNAPL\pytorch_model.bin.index.json
j:\GPTAI\CNAPL\pytorch_model-00001-of-00003.bin
j:\GPTAI\CNAPL\pytorch_model-00002-of-00003.bin
j:\GPTAI\CNAPL\pytorch_model-00003-of-00003.bin
j:\GPTAI\CNAPL\special_tokens_map.json
j:\GPTAI\CNAPL\tokenizer.model
j:\GPTAI\CNAPL\tokenizer_config.json
j:\GPTAI\llama-13b-hf\.gitattributes
j:\GPTAI\llama-13b-hf\config.json
j:\GPTAI\llama-13b-hf\generation_config.json
j:\GPTAI\llama-13b-hf\LICENSE
j:\GPTAI\llama-13b-hf\pytorch_model.bin.index.json
j:\GPTAI\llama-13b-hf\pytorch_model-00000-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00001-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00002-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00003-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00004-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00005-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00006-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00007-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00008-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00009-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00010-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00011-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00012-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00013-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00014-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00015-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00016-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00017-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00018-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00019-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00020-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00021-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00022-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00023-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00024-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00025-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00026-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00027-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00028-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00029-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00030-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00031-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00032-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00033-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00034-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00035-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00036-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00037-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00038-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00039-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00040-of-00041.bin
j:\GPTAI\llama-13b-hf\pytorch_model-00041-of-00041.bin
j:\GPTAI\llama-13b-hf\README.md
j:\GPTAI\llama-13b-hf\special_tokens_map.json
j:\GPTAI\llama-13b-hf\tokenizer.model
j:\GPTAI\llama-13b-hf\tokenizer_config.json
j:\GPTAI\script\chinese_sp.model
j:\GPTAI\script\convert_llama_weights_to_hf.py
j:\GPTAI\script\crawl_prompt.py
j:\GPTAI\script\inference_hf.py
j:\GPTAI\script\merge_llama_with_chinese_lora.py
j:\GPTAI\script\merge_tokenizers.py
j:\GPTAI\script\run_clm_pt_with_peft.py
```

可以看到錯誤分為兩部分

```
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'J:\GPTAI\CNAPL'.
```
以及
```
ValueError: Can't find weights for J:\GPTAI\CNAPL in J:\GPTAI\CNAPL or in the Hugging Face Hub. Please check that the file adapter_model.bin is present at J:\GPTAI\CNAPL.
```
### 必查项目（前三项只保留你要问的）

- [x ] **基础模型**：Alpaca-Plus
- [x ] **运行系统**：Windows
- [x ] **问题分类**：模型推理问题（🤗 transformers）
- [x ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
`J:\GPTAI\CNAPL`下有哪些文件？

**Comment by CRGBS** [comment]
> `J:\GPTAI\CNAPL`下有哪些文件？

j:\GPTAI\CNAPL\adapter_config.json
j:\GPTAI\CNAPL\config.json
j:\GPTAI\CNAPL\generation_config.json
j:\GPTAI\CNAPL\pytorch_model.bin.index.json
j:\GPTAI\CNAPL\pytorch_model-00001-of-00003.bin
j:\GPTAI\CNAPL\pytorch_model-00002-of-00003.bin
j:\GPTAI\CNAPL\pytorch_model-00003-of-00003.bin
j:\GPTAI\CNAPL\special_tokens_map.json
j:\GPTAI\CNAPL\tokenizer.model
j:\GPTAI\CNAPL\tokenizer_config.json

**Comment by ymcui** [comment]
1、Alpaca-Plus-LoRA无法直接通过inference_hf.py加载，需要先进行模型合并。
2、如果你的`J:\GPTAI\CNAPL`已经是合并后的模型了，就不要以lora方式传入了，只需要指定base_model。

仔细阅读一下Wiki：https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/使用Transformers推理

**Comment by CRGBS** [comment]
> 1、Alpaca-Plus-LoRA无法直接通过inference_hf.py加载，需要先进行模型合并。 2、如果你的`J:\GPTAI\CNAPL`已经是合并后的模型了，就不要以lora方式传入了，只需要指定base_model。
> 
> 仔细阅读一下Wiki：[https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/使用Transformers推理](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E4%BD%BF%E7%94%A8Transformers%E6%8E%A8%E7%90%86)
感謝回復 由於base以及lora model搞混才導致今次的錯誤
