### ISSUE TITLE
deepspeed训练报错

### ISSUE THREAD

**Issue by ccdf1137** [ymcui/Chinese-LLaMA-Alpaca#354]
GPU：1台机器，8张A800，cuda：11.7
训练启动参数：
lr=2e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/workspace/fumengen/works/Chinese-LLaMA-Alpaca/models/chinese_llama_13b
chinese_tokenizer_path=/workspace/fumengen/works/Chinese-LLaMA-Alpaca/models/chinese_llama_13b
dataset_dir=/workspace/fumengen/works/Chinese-LLaMA-Alpaca/data/cn_pretrain_data
data_cache=/workspace/fumengen/works/Chinese-LLaMA-Alpaca/data/data_tmp
per_device_train_batch_size=2
per_device_eval_batch_size=2
training_steps=100
gradient_accumulation_steps=8
output_dir=/workspace/fumengen/works/Chinese-LLaMA-Alpaca/outputs

deepspeed_config_file=/workspace/fumengen/works/Chinese-LLaMA-Alpaca/ds_config.json

torchrun --nnodes 1 --nproc_per_node 8 scripts/run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed 3407 \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 500 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False

Deepspeed_config参数

{
    "bfloat16": {
        "enabled": "auto"
    },
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },
    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto"
        }
    },
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": true
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "steps_per_print": 1e5
}

报错bug：
05/17/2023 09:23:35 - INFO - __main__ - training datasets-test_1187 has been loaded from disk
05/17/2023 09:23:35 - INFO - datasets.arrow_dataset - Caching indices mapping at /workspace/fumengen/works/Chinese-LLaMA-Alpaca/data/data_tmp/test_898/train/cache-edb7bf906025b5f5.arrow
05/17/2023 09:23:35 - INFO - datasets.arrow_dataset - Caching indices mapping at /workspace/fumengen/works/Chinese-LLaMA-Alpaca/data/data_tmp/test_898/train/cache-5cacbc341600c89e.arrow
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 124 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 126 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 127 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 1 (pid: 123) of binary: /workspace/fumengen/vir_fme/bin/python3.10
Traceback (most recent call last):
  File "/workspace/fumengen/vir_fme/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

scripts/run_clm_pt_with_peft.py FAILED

Failures:
[1]:
  time      : 2023-05-17_09:23:42
  host      : 7b4985eaff35
  rank      : 3 (local_rank: 3)
  exitcode  : -7 (pid: 125)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 125
[2]:
  time      : 2023-05-17_09:23:42
  host      : 7b4985eaff35
  rank      : 6 (local_rank: 6)
  exitcode  : -7 (pid: 128)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 128
[3]:
  time      : 2023-05-17_09:23:42
  host      : 7b4985eaff35
  rank      : 7 (local_rank: 7)
  exitcode  : -7 (pid: 129)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 129
---------------------------------------------------

**Comment by airaria** [comment]
把缓存`/workspace/fumengen/works/Chinese-LLaMA-Alpaca/data/data_tmp/test_898`删掉让程序重新生成一次试试

**Comment by iMountTai** [comment]
关注一下内存的变化，可能是内存不足

**Comment by ccdf1137** [comment]
@airaria 重新生成同样的报错

**Comment by airaria** [comment]
> @airaria 重新生成同样的报错

现在不清楚是哪里的问题，建议通过实验准确定位。
比如，用小数据集、单卡有没有问题？

**Comment by airaria** [comment]
> @airaria 重新生成同样的报错


参考iMountTai的建议

> 关注一下内存的变化，可能是内存不足

**Comment by ccdf1137** [comment]
@iMountTai    
![d5425278d767937e5a7f8a718f5a5cd](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/133088297/877a6654-6a07-4207-b544-679743a0c89b)
![8f7fea83f5663b5a6ea8d4eda0ea97b](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/133088297/edb33c92-72f2-424c-a4bb-ea4612cf0a31)
这是运行时  GPU和CPU的状态

**Comment by iMountTai** [comment]
1T的内存确实不应该不足，建议您先完全按照我们的脚本设置运行7B的模型训练，然后再按照您的意愿修改相关设置

**Comment by ccdf1137** [comment]
@iMountTai     这是我下载合并的chinese-llama-7b的模型运行的，脚本没改只用1个gpu，torchrun --nnodes 1 --nproc_per_node 1 ，报错如下，如果使用多个gpu的话，报错还是跟上面的一样。
报错：
05/17/2023 17:02:39 - INFO - datasets.arrow_dataset - Process #7 will write at /workspace/fumengen/works/Chinese-LLaMA-Alpaca/data/cache/cache_7b/test_245_text/tokenized_00007_of_00008.arrow
Traceback (most recent call last):
  File "/workspace/fumengen/works/Chinese-LLaMA-Alpaca/scripts/run_clm_pt_with_peft.py", line 461, in main
    processed_dataset = datasets.load_from_disk(cache_path, keep_in_memory=False)
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/datasets/load.py", line 1894, in load_from_disk
    raise FileNotFoundError(
**FileNotFoundError: Directory /workspace/fumengen/works/Chinese-LLaMA-Alpaca/data/cache/cache_7b/test_245 is neither a `Dataset` directory nor a `DatasetDict` directory.**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/fumengen/works/Chinese-LLaMA-Alpaca/scripts/run_clm_pt_with_peft.py", line 622, in <module>
    main()
  File "/workspace/fumengen/works/Chinese-LLaMA-Alpaca/scripts/run_clm_pt_with_peft.py", line 468, in main
    tokenized_dataset = raw_dataset.map(
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/datasets/dataset_dict.py", line 851, in map
    {
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/datasets/dataset_dict.py", line 852, in <dictcomp>
    k: dataset.map(
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 578, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 543, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3156, in map
    with Pool(len(kwargs_per_job)) as pool:
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/multiprocess/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/multiprocess/pool.py", line 191, in __init__
    self._setup_queues()
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/multiprocess/pool.py", line 346, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/multiprocess/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/multiprocess/queues.py", line 344, in __init__
    self._rlock = ctx.Lock()
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/multiprocess/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/multiprocess/synchronize.py", line 168, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/multiprocess/synchronize.py", line 63, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
**OSError: [Errno 28] No space left on device**
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 13913) of binary: /workspace/fumengen/vir_fme/bin/python3.10
Traceback (most recent call last):
  File "/workspace/fumengen/vir_fme/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/workspace/fumengen/vir_fme/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
run_clm_pt_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-17_17:02:43
  host      : 7b4985eaff35
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 13913)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by ccdf1137** [comment]
我把docker 容器关了又重新开一下，就好了

**Comment by dhhcj** [comment]
> 我把docker 容器关了又重新开一下，就好了

老哥，batch size为1时单卡的显存能到多生呀，我用8块A100（40g）能起来吗？

**Comment by ccdf1137** [comment]
@dhhcj 
用deepspeed  stage=2    cpu内存换显存  
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/133088297/8e2adabe-396a-41d2-b4a2-51a73aaff9f9)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/133088297/af4aec1b-d652-4584-8218-fa2f6ba60dea)
你看你内存容量够不够

**Comment by dhhcj** [comment]
> stage

这块是怎么调整的呀，我没有在脚本和配置文件里发现相关参数

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/26632100/9eebf188-20b7-4457-9210-81862e6a9ec8)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/26632100/642ef18c-4bc0-4824-94a4-57de18fabdde)

**Comment by ccdf1137** [comment]
DeepSpeed官方文档有教程的，你这就行
