### ISSUE TITLE
运行推理出错

### ISSUE THREAD

**Issue by sliontc** [ymcui/Chinese-LLaMA-Alpaca#448]
### 详细描述问题

输入一句中文请求后，出现如下错误：

### 运行截图或日志

*请提供文本log或者运行截图，以便我们更好地了解问题详情。*
llama_tokenize: too many tokens
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\privateGPT-main\privateGPT.py", line 81, in <module>
    main()
  File "C:\Users\Administrator\Desktop\privateGPT-main\privateGPT.py", line 53, in main
    res = qa(query)
          ^^^^^^^^^
  File "D:\python311\Lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "D:\python311\Lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\python311\Lib\site-packages\langchain\chains\retrieval_qa\base.py", line 120, in _call
    answer = self.combine_documents_chain.run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\langchain\chains\base.py", line 239, in run
    return self(kwargs, callbacks=callbacks)[self.output_keys[0]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "D:\python311\Lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\python311\Lib\site-packages\langchain\chains\combine_documents\base.py", line 84, in _call
    output, extra_return_dict = self.combine_docs(
                                ^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\langchain\chains\combine_documents\stuff.py", line 87, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\langchain\chains\llm.py", line 213, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "D:\python311\Lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\python311\Lib\site-packages\langchain\chains\llm.py", line 69, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\langchain\chains\llm.py", line 79, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\langchain\llms\base.py", line 134, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\langchain\llms\base.py", line 191, in generate
    raise e
  File "D:\python311\Lib\site-packages\langchain\llms\base.py", line 185, in generate
    self._generate(prompts, stop=stop, run_manager=run_manager)
  File "D:\python311\Lib\site-packages\langchain\llms\base.py", line 411, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager)
  File "D:\python311\Lib\site-packages\langchain\llms\llamacpp.py", line 225, in _call
    for token in self.stream(prompt=prompt, stop=stop, run_manager=run_manager):
  File "D:\python311\Lib\site-packages\langchain\llms\llamacpp.py", line 274, in stream
    for chunk in result:
  File "D:\python311\Lib\site-packages\llama_cpp\llama.py", line 618, in _create_completion
    raise ValueError(
ValueError: Requested tokens exceed context window of 2048
### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：LLaMA
- [ ] **运行系统**：Windows，Python3.11
- [ ] **问题分类**：模型推理问题
- [ ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by ymcui** [comment]
你输入的query是什么？从提示看是你的context超过最大长度2048了。

**Comment by sliontc** [comment]
> 你输入的query是什么？从提示看是你的context超过最大长度2048了。
随便输入一个中文，都这样

**Comment by sliontc** [comment]
我是在privateGPT里运行的，ingest是成功的

**Comment by airaria** [comment]
是不是你的文档段落都太长了？用短文档先试试？

**Comment by ymcui** [comment]
参考：https://github.com/imartinez/privateGPT/issues/375
