### ISSUE TITLE
[BUG?]TypeError: 'LoraConfig' object is not subscriptable

### ISSUE THREAD

**Issue by runzhi214** [ymcui/Chinese-LLaMA-Alpaca#474]
*提示：将[ ]中填入x，表示打对钩。提问时删除这行。只保留符合的选项。*

### 详细描述问题
按照[预训练wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E9%A2%84%E8%AE%AD%E7%BB%83%E8%84%9A%E6%9C%AC)的描述：安装了[commit id为13e53fc的Peft](https://github.com/huggingface/peft/tree/13e53fc)
但是在运行完run_pt.sh之后报错，无法保存Lora参数
核心就是这一句：` unwrap_model(model).peft_config['default'].save_pretrained(lora_path)`
确定这个peft_config['default']是要求的这个Peft允许的吗？

### 运行截图或日志
报错信息如下：

> [INFO|trainer.py:2904] 2023-05-31 15:45:14,806 >> Saving model checkpoint to /data/models/llama_origin_elec
[INFO|trainer.py:2916] 2023-05-31 15:45:14,809 >> Trainer.model is not a `PreTrainedModel`, only saving its state dict.
[INFO|tokenization_utils_base.py:2181] 2023-05-31 15:45:14,861 >> tokenizer config file saved in /data/models/llama_origin_elec/tokenizer_config.json
[INFO|tokenization_utils_base.py:2188] 2023-05-31 15:45:14,861 >> Special tokens file saved in /data/models/llama_origin_elec/special_tokens_map.json
***** train metrics *****
  epoch                    =       0.31
  train_loss               =     7.0228
  train_runtime            = 0:00:36.95
  train_samples            =        320
  train_samples_per_second =      2.706
  train_steps_per_second   =      2.706
Traceback (most recent call last):
  File "/data/models/Chinese-LLaMA-Alpaca/scripts/run_clm_pt_with_peft.py", line 632, in <module>
    main()
  File "/data/models/Chinese-LLaMA-Alpaca/scripts/run_clm_pt_with_peft.py", line 605, in main
    unwrap_model(model).peft_config['default'].save_pretrained(lora_path)
TypeError: 'LoraConfig' object is not subscriptable
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 41567) of binary: /home/runzhi/anaconda3/envs/py39/bin/python
Traceback (most recent call last):
  File "/home/runzhi/anaconda3/envs/py39/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())
  File "/home/runzhi/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/runzhi/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/runzhi/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/runzhi/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/runzhi/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
run_clm_pt_with_peft.py FAILED
Failures:
  <NO_OTHER_FAILURES>

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：LLaMA-Plus
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型训练与精调 
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：无第三方插件

**Comment by airaria** [comment]
的确，这个版本的peft直接`model.peft_config.save_pretrained`就可以了
感谢指出bug；你可以先按照[wiki的说明](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/预训练脚本#训练后文件整理)的手动准备adapter_config.json

**Comment by xiaozhu1106** [comment]
遇到同样问题，请教一下，这个如何处理的？

**Comment by runzhi214** [comment]
> unwrap_model(model).peft_config['default'].save_pretrained(lora_path)

把run_clm_pt那个脚本报错的那一行改为`unwrap_model(model).peft_config['default'].save_pretrained(lora_path)`
