### ISSUE TITLE
预训练启动失败，日志停在Initializing TorchBackend in DeepSpeed with backend nccl

### ISSUE THREAD

**Issue by tomjamescn** [ymcui/Chinese-LLaMA-Alpaca#545]
### 详细描述问题

使用预训练脚本时，出现deepspeed启动等待，并启动失败的情况。

#### 依赖情况（代码类问题务必提供）

```
Package                  Version
------------------------ ----------
accelerate               0.19.0
aiofiles                 23.1.0
aiohttp                  3.8.4
aiosignal                1.3.1
altair                   5.0.0
anyio                    3.6.2
async-timeout            4.0.2
attrs                    23.1.0
certifi                  2023.5.7
charset-normalizer       3.1.0
click                    8.1.3
cmake                    3.26.3
contourpy                1.0.7
cycler                   0.11.0
datasets                 2.12.0
deepspeed                0.9.2
dill                     0.3.6
fastapi                  0.95.1
ffmpy                    0.3.0
filelock                 3.12.0
fonttools                4.39.4
frozenlist               1.3.3
fsspec                   2023.5.0
gradio                   3.30.0
gradio_client            0.2.4
h11                      0.14.0
hjson                    3.1.0
httpcore                 0.17.0
httpx                    0.24.0
huggingface-hub          0.14.1
idna                     3.4
Jinja2                   3.1.2
joblib                   1.2.0
jsonschema               4.17.3
kiwisolver               1.4.4
latex2mathml             3.75.5
linkify-it-py            2.0.2
lit                      16.0.3
Markdown                 3.4.3
markdown-it-py           2.2.0
MarkupSafe               2.1.2
matplotlib               3.7.1
mdit-py-plugins          0.3.3
mdtex2html               1.2.0
mdurl                    0.1.2
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.14
networkx                 3.1
ninja                    1.11.1
numpy                    1.24.3
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
orjson                   3.8.12
packaging                23.1
pandas                   2.0.1
peft                     0.3.0
Pillow                   9.5.0
pip                      23.0.1
psutil                   5.9.5
py-cpuinfo               9.0.0
pyarrow                  12.0.0
pydantic                 1.10.7
pydub                    0.25.1
Pygments                 2.15.1
pyparsing                3.0.9
pyrsistent               0.19.3
python-dateutil          2.8.2
python-multipart         0.0.6
pytz                     2023.3
PyYAML                   6.0
regex                    2023.5.5
requests                 2.30.0
responses                0.18.0
scikit-learn             1.2.2
scipy                    1.10.1
semantic-version         2.10.0
sentencepiece            0.1.97
setuptools               67.8.0
six                      1.16.0
sniffio                  1.3.0
starlette                0.26.1
sympy                    1.12
threadpoolctl            3.1.0
tokenizers               0.13.3
toolz                    0.12.0
torch                    1.13.1
tqdm                     4.65.0
transformers             4.28.1
triton                   2.0.0
typing_extensions        4.5.0
tzdata                   2023.3
uc-micro-py              1.0.2
urllib3                  2.0.2
uvicorn                  0.22.0
websockets               11.0.3
wheel                    0.38.4
xxhash                   3.2.0
yarl                     1.9.2
```

run_pt.sh配置如下
```
lr=2e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/data/Chinese-LLaMA-Alpaca/models/13B
chinese_tokenizer_path=/data/Chinese-LLaMA-Alpaca/models/13B
dataset_dir=/data/Chinese-LLaMA-Alpaca/data/js
data_cache=temp_data_cache_dir
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=100
gradient_accumulation_steps=1
output_dir=/data/Chinese-LLaMA-Alpaca/models/13B.train

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 1 run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed $RANDOM \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 500 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 10 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False
```

#### 运行日志或截图

```
# bash run_pt.sh
[2023-06-09 11:07:49,777] [INFO] [comm.py:622:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
^CWARNING:torch.distributed.elastic.agent.server.api:Received 2 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21287 closing signal SIGINT

Traceback (most recent call last):
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 237, in launch_agent
    result = agent.run()
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 850, in _invoke_run
    time.sleep(monitor_interval)
  File "/root/miniconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 21212 got signal: 2
```

### 必查项目

*将[ ]中填入x，表示打对钩。提问时删除这行。 前三项请按自己的问题类型保留符合的选项。*

- [√ ] **基础模型**：Alpaca-Plus 13B
- [√] **运行系统**：Linux 
- [√ ] **问题分类**：模型训练与精调 
- [√] **模型正确性检查**：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行。
- [√] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [√] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案

**Comment by iMountTai** [comment]
`--ddp_timeout 1800` 试试
