### ISSUE TITLE
deepspeed安装不了

### ISSUE THREAD

**Issue by Canyao45** [ymcui/Chinese-LLaMA-Alpaca#603]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

None

### 操作系统

Windows

### 详细描述问题

运行精炼就报错这个安装deepspeed一直安装不了纯新手

### 运行日志或截图

NOTE: Redirects are currently not supported in Windows or MacOs.
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-DSOBSQV]:29500 (system error: 10049 - ▒▒▒▒▒▒▒▒▒▒▒У▒▒▒▒▒▒▒ĵ▒ַ▒▒Ч▒▒).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-DSOBSQV]:29500 (system error: 10049 - ▒▒▒▒▒▒▒▒▒▒▒У▒▒▒▒▒▒▒ĵ▒ַ▒▒Ч▒▒).
Traceback (most recent call last):
  File "E:\Chinese-LLaMA-Alpaca-main-1\Chinese-LLaMA-Alpaca-main\scripts\training\run_clm_sft_with_peft.py", line 472, in <module>
    main()
  File "E:\Chinese-LLaMA-Alpaca-main-1\Chinese-LLaMA-Alpaca-main\scripts\training\run_clm_sft_with_peft.py", line 228, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\hf_argparser.py", line 332, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 117, in __init__
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\training_args.py", line 1259, in __post_init__
    and (self.device.type != "cuda")
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\training_args.py", line 1694, in device
    return self._setup_devices
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\utils\generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\training_args.py", line 1623, in _setup_devices
    raise ImportError("--deepspeed requires deepspeed: `pip install deepspeed`.")
ImportError: --deepspeed requires deepspeed: `pip install deepspeed`.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 52828) of binary: C:\Users\shipin\AppData\Local\Programs\Python\Python39\python.exe
Traceback (most recent call last):
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\run.py", line 794, in main
    run(args)
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\run.py", line 785, in run
    elastic_launch(
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\shipin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
run_clm_sft_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-15_17:16:52
  host      : DESKTOP-DSOBSQV
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 52828)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by Canyao45** [comment]
好的，有没有解决方案呢

**Comment by AceyKubbo** [comment]
> 好的，有没有解决方案呢

window没办法,你自能考虑用wsl安装ubuntu进行
