### ISSUE TITLE
一机多卡预训练和精调

### ISSUE THREAD

**Issue by zzx16045223** [ymcui/Chinese-LLaMA-Alpaca#637]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

--nproc_per_node 如果设置为2时，可以正常运行，但是设置为8时，会出错

### 依赖情况（代码类问题务必提供）

absl-py                     1.4.0
accelerate                  0.20.3
aiofiles                    23.1.0
aiohttp                     3.8.4
aiosignal                   1.3.1
altair                      5.0.1
antlr4-python3-runtime      4.9.3
anyio                       3.7.0
appdirs                     1.4.4
asttokens                   2.0.5
astunparse                  1.6.3
async-timeout               4.0.2
attrs                       23.1.0
automaton                   3.1.0
Babel                       2.12.1
backcall                    0.2.0
bce-python-sdk              0.8.83
beautifulsoup4              4.12.2
blinker                     1.6.2
boltons                     23.0.0
boto3                       1.21.42
botocore                    1.24.46
brotlipy                    0.7.0
bs4                         0.0.1
cachetools                  5.3.1
certifi                     2023.5.7
cffi                        1.15.1
chardet                     4.0.0
charset-normalizer          2.0.4
click                       8.1.3
cmake                       3.25.0
cobble                      0.1.3
colorama                    0.4.6
colorlog                    6.7.0
conda                       23.3.1
conda-build                 3.24.0
conda-content-trust         0.1.3
conda-package-handling      2.0.2
conda_package_streaming     0.7.0
contourpy                   1.0.7
cryptography                39.0.1
cycler                      0.11.0
datasets                    2.10.1
debtcollector               2.5.0
decorator                   5.1.1
deepspeed                   0.9.4
diffusers                   0.7.2
dill                        0.3.4
dnspython                   2.3.0
docker-pycreds              0.4.0
docx                        0.2.4
docx2txt                    0.8
einops                      0.3.0
exceptiongroup              1.1.1
executing                   0.8.3
expecttest                  0.1.4
fastapi                     0.97.0
fasteners                   0.18
ffmpy                       0.3.0
filelock                    3.9.0
flagai                      1.7.2
Flask                       2.3.2
Flask-Babel                 2.0.0
fonttools                   4.40.0
frozenlist                  1.3.3
fschat                      0.2.13       /zzx/FastChat
fsspec                      2023.6.0
ftfy                        6.1.1
future                      0.18.3
futurist                    2.4.1
gitdb                       4.0.10
GitPython                   3.1.31
glob2                       0.7
gmpy2                       2.1.2
google-auth                 2.20.0
google-auth-oauthlib        0.4.6
gradio                      3.23.0
grpcio                      1.54.2
h11                         0.14.0
hjson                       3.1.0
httpcore                    0.17.2
httpx                       0.24.1
huggingface-hub             0.15.1
hypothesis                  6.75.2
idna                        3.4
importlib-metadata          6.6.0
ipython                     8.12.0
iso8601                     2.0.0
itsdangerous                2.1.2
jedi                        0.18.1
jieba                       0.42.1
Jinja2                      3.1.2
jmespath                    1.0.1
joblib                      1.2.0
jsonpatch                   1.32
jsonpointer                 2.1
jsonschema                  4.17.3
kiwisolver                  1.4.4
libarchive-c                2.9
linkify-it-py               2.0.2
lit                         15.0.7
lxml                        4.9.2
mammoth                     1.6.0
Markdown                    3.4.3
markdown-it-py              2.2.0
markdown2                   2.4.8
MarkupSafe                  2.1.1
matplotlib                  3.7.1
matplotlib-inline           0.1.6
mdit-py-plugins             0.3.3
mdurl                       0.1.2
mkl-fft                     1.3.6
mkl-random                  1.2.2
mkl-service                 2.4.0
mpmath                      1.3.0
msgpack                     1.0.5
multidict                   6.0.4
multiprocess                0.70.12.2
netaddr                     0.8.0
netifaces                   0.11.0
networkx                    2.8.4
nh3                         0.2.13
ninja                       1.11.1
nltk                        3.6.7
numpy                       1.24.3
oauthlib                    3.2.2
omegaconf                   2.3.0
orjson                      3.9.1
oslo.i18n                   6.0.0
oslo.serialization          5.1.1
oslo.utils                  6.1.0
packaging                   23.0
paddle2onnx                 1.0.6
paddlefsl                   1.1.0
paddlenlp                   2.5.2
pandas                      1.3.5
parso                       0.8.3
pathtools                   0.1.2
pbr                         5.11.1
peft                        0.3.0.dev0
pexpect                     4.8.0
pickleshare                 0.7.5
Pillow                      9.4.0
pip                         23.1.2
pkginfo                     1.9.6
pluggy                      1.0.0
portalocker                 2.7.0
prettytable                 3.8.0
prompt-toolkit              3.0.36
protobuf                    3.19.6
psutil                      5.9.0
ptyprocess                  0.7.0
pure-eval                   0.2.2
py-cpuinfo                  9.0.0
pyarrow                     12.0.1
pyasn1                      0.5.0
pyasn1-modules              0.3.0
pycosat                     0.6.4
pycparser                   2.21
pycryptodome                3.18.0
pydantic                    1.10.9
pyDeprecate                 0.3.2
pydot                       1.4.2
pydub                       0.25.1
Pygments                    2.15.1
pyOpenSSL                   23.0.0
pyparsing                   3.0.9
pyrsistent                  0.19.3
PySocks                     1.7.1
python-dateutil             2.8.2
python-docx                 0.8.11
python-etcd                 0.4.5
python-multipart            0.0.6
pytorch-lightning           1.6.5
pytz                        2022.7
PyYAML                      6.0
regex                       2023.6.3
requests                    2.29.0
requests-oauthlib           1.3.1
responses                   0.18.0
rich                        13.4.2
rouge-score                 0.1.2
rsa                         4.9
ruamel.yaml                 0.17.21
ruamel.yaml.clib            0.2.6
s3transfer                  0.5.2
sacrebleu                   2.3.1
scikit-learn                1.0.2
scipy                       1.10.1
semantic-version            2.10.0
sentencepiece               0.1.97
sentry-sdk                  1.25.1
seqeval                     1.2.2
setproctitle                1.3.2
setuptools                  59.5.0
shortuuid                   1.0.11
six                         1.16.0
smmap                       5.0.0
sniffio                     1.3.0
sortedcontainers            2.4.0
soupsieve                   2.4
stack-data                  0.2.0
starlette                   0.27.0
stevedore                   5.1.0
svgwrite                    1.4.3
sympy                       1.11.1
tabulate                    0.9.0
taming-transformers-rom1504 0.0.6
taskflow                    5.2.0
tenacity                    8.2.2
tensorboard                 2.9.0
tensorboard-data-server     0.6.1
tensorboard-plugin-wit      1.8.1
threadpoolctl               3.1.0
tiktoken                    0.4.0
tokenizers                  0.13.3
tomli                       2.0.1
toolz                       0.12.0
torch                       2.0.0+cu118
torchaudio                  2.0.1+cu118
torchdata                   0.6.1
torchelastic                0.2.2
torchmetrics                0.11.4
torchtext                   0.15.2
torchvision                 0.15.1+cu118
tqdm                        4.65.0
traitlets                   5.7.1
transformers                4.28.1
transforms                  0.1
triton                      2.0.0
typer                       0.9.0
types-dataclasses           0.6.6
typing_extensions           4.5.0
tzdata                      2023.3
uc-micro-py                 1.0.2
urllib3                     1.26.15
uvicorn                     0.22.0
visualdl                    2.4.2
wandb                       0.15.4
wavedrom                    2.0.3.post3
wcwidth                     0.2.5
websockets                  11.0.3
Werkzeug                    2.3.6
wheel                       0.38.4
wrapt                       1.15.0
xxhash                      3.2.0
yarl                        1.9.2
zipp                        3.15.0
zstandard                   0.19.0

### 运行日志或截图

[INFO|trainer.py:564] 2023-06-19 14:32:51,647 >> max_steps is given, it will override any value given in num_train_epochs
[INFO|trainer.py:621] 2023-06-19 14:32:51,658 >> Using cuda_amp half precision backend
trainable params: 569131008 || all params: 7045402624 || trainable%: 8.078048031794074
trainable params: 569131008 || all params: 7045402624 || trainable%: 8.078048031794074
trainable params: 569131008 || all params: 7045402624 || trainable%: 8.078048031794074
/opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
trainable params: 569131008 || all params: 7045402624 || trainable%: 8.078048031794074
/opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
[2023-06-19 14:32:51,761] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.9.4, git-hash=unknown, git-branch=unknown
trainable params: 569131008 || all params: 7045402624 || trainable%: 8.078048031794074
/opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
trainable params: 569131008 || all params: 7045402624 || trainable%: 8.078048031794074
/opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7583 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7584 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7585 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7586 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7587 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7588 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7589 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 7 (pid: 7590) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
run_clm_sft_with_peft.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-19_14:32:53
  host      : 5ea5c16a9c40
  rank      : 7 (local_rank: 7)
  exitcode  : -9 (pid: 7590)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 7590
=====================================================

![dcd2f15550aa68ef9eb7abb59ad7fa3](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/46176408/f0330430-b8fc-49e1-aba9-74488d42dac3)

**Comment by zzx16045223** [comment]
> ### 提交前必须检查以下项目
> * [x]  请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
> * [x]  由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
> * [x]  我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
> * [x]  第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
> * [x]  模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行
> 
> ### 问题类型
> 模型训练与精调
> 
> ### 基础模型
> LLaMA-7B
> 
> ### 操作系统
> Linux
> 
> ### 详细描述问题
> --nproc_per_node 如果设置为2时，可以正常运行，但是设置为8时，会出错
> 
> ### 依赖情况（代码类问题务必提供）
> absl-py 1.4.0 accelerate 0.20.3 aiofiles 23.1.0 aiohttp 3.8.4 aiosignal 1.3.1 altair 5.0.1 antlr4-python3-runtime 4.9.3 anyio 3.7.0 appdirs 1.4.4 asttokens 2.0.5 astunparse 1.6.3 async-timeout 4.0.2 attrs 23.1.0 automaton 3.1.0 Babel 2.12.1 backcall 0.2.0 bce-python-sdk 0.8.83 beautifulsoup4 4.12.2 blinker 1.6.2 boltons 23.0.0 boto3 1.21.42 botocore 1.24.46 brotlipy 0.7.0 bs4 0.0.1 cachetools 5.3.1 certifi 2023.5.7 cffi 1.15.1 chardet 4.0.0 charset-normalizer 2.0.4 click 8.1.3 cmake 3.25.0 cobble 0.1.3 colorama 0.4.6 colorlog 6.7.0 conda 23.3.1 conda-build 3.24.0 conda-content-trust 0.1.3 conda-package-handling 2.0.2 conda_package_streaming 0.7.0 contourpy 1.0.7 cryptography 39.0.1 cycler 0.11.0 datasets 2.10.1 debtcollector 2.5.0 decorator 5.1.1 deepspeed 0.9.4 diffusers 0.7.2 dill 0.3.4 dnspython 2.3.0 docker-pycreds 0.4.0 docx 0.2.4 docx2txt 0.8 einops 0.3.0 exceptiongroup 1.1.1 executing 0.8.3 expecttest 0.1.4 fastapi 0.97.0 fasteners 0.18 ffmpy 0.3.0 filelock 3.9.0 flagai 1.7.2 Flask 2.3.2 Flask-Babel 2.0.0 fonttools 4.40.0 frozenlist 1.3.3 fschat 0.2.13 /zzx/FastChat fsspec 2023.6.0 ftfy 6.1.1 future 0.18.3 futurist 2.4.1 gitdb 4.0.10 GitPython 3.1.31 glob2 0.7 gmpy2 2.1.2 google-auth 2.20.0 google-auth-oauthlib 0.4.6 gradio 3.23.0 grpcio 1.54.2 h11 0.14.0 hjson 3.1.0 httpcore 0.17.2 httpx 0.24.1 huggingface-hub 0.15.1 hypothesis 6.75.2 idna 3.4 importlib-metadata 6.6.0 ipython 8.12.0 iso8601 2.0.0 itsdangerous 2.1.2 jedi 0.18.1 jieba 0.42.1 Jinja2 3.1.2 jmespath 1.0.1 joblib 1.2.0 jsonpatch 1.32 jsonpointer 2.1 jsonschema 4.17.3 kiwisolver 1.4.4 libarchive-c 2.9 linkify-it-py 2.0.2 lit 15.0.7 lxml 4.9.2 mammoth 1.6.0 Markdown 3.4.3 markdown-it-py 2.2.0 markdown2 2.4.8 MarkupSafe 2.1.1 matplotlib 3.7.1 matplotlib-inline 0.1.6 mdit-py-plugins 0.3.3 mdurl 0.1.2 mkl-fft 1.3.6 mkl-random 1.2.2 mkl-service 2.4.0 mpmath 1.3.0 msgpack 1.0.5 multidict 6.0.4 multiprocess 0.70.12.2 netaddr 0.8.0 netifaces 0.11.0 networkx 2.8.4 nh3 0.2.13 ninja 1.11.1 nltk 3.6.7 numpy 1.24.3 oauthlib 3.2.2 omegaconf 2.3.0 orjson 3.9.1 oslo.i18n 6.0.0 oslo.serialization 5.1.1 oslo.utils 6.1.0 packaging 23.0 paddle2onnx 1.0.6 paddlefsl 1.1.0 paddlenlp 2.5.2 pandas 1.3.5 parso 0.8.3 pathtools 0.1.2 pbr 5.11.1 peft 0.3.0.dev0 pexpect 4.8.0 pickleshare 0.7.5 Pillow 9.4.0 pip 23.1.2 pkginfo 1.9.6 pluggy 1.0.0 portalocker 2.7.0 prettytable 3.8.0 prompt-toolkit 3.0.36 protobuf 3.19.6 psutil 5.9.0 ptyprocess 0.7.0 pure-eval 0.2.2 py-cpuinfo 9.0.0 pyarrow 12.0.1 pyasn1 0.5.0 pyasn1-modules 0.3.0 pycosat 0.6.4 pycparser 2.21 pycryptodome 3.18.0 pydantic 1.10.9 pyDeprecate 0.3.2 pydot 1.4.2 pydub 0.25.1 Pygments 2.15.1 pyOpenSSL 23.0.0 pyparsing 3.0.9 pyrsistent 0.19.3 PySocks 1.7.1 python-dateutil 2.8.2 python-docx 0.8.11 python-etcd 0.4.5 python-multipart 0.0.6 pytorch-lightning 1.6.5 pytz 2022.7 PyYAML 6.0 regex 2023.6.3 requests 2.29.0 requests-oauthlib 1.3.1 responses 0.18.0 rich 13.4.2 rouge-score 0.1.2 rsa 4.9 ruamel.yaml 0.17.21 ruamel.yaml.clib 0.2.6 s3transfer 0.5.2 sacrebleu 2.3.1 scikit-learn 1.0.2 scipy 1.10.1 semantic-version 2.10.0 sentencepiece 0.1.97 sentry-sdk 1.25.1 seqeval 1.2.2 setproctitle 1.3.2 setuptools 59.5.0 shortuuid 1.0.11 six 1.16.0 smmap 5.0.0 sniffio 1.3.0 sortedcontainers 2.4.0 soupsieve 2.4 stack-data 0.2.0 starlette 0.27.0 stevedore 5.1.0 svgwrite 1.4.3 sympy 1.11.1 tabulate 0.9.0 taming-transformers-rom1504 0.0.6 taskflow 5.2.0 tenacity 8.2.2 tensorboard 2.9.0 tensorboard-data-server 0.6.1 tensorboard-plugin-wit 1.8.1 threadpoolctl 3.1.0 tiktoken 0.4.0 tokenizers 0.13.3 tomli 2.0.1 toolz 0.12.0 torch 2.0.0+cu118 torchaudio 2.0.1+cu118 torchdata 0.6.1 torchelastic 0.2.2 torchmetrics 0.11.4 torchtext 0.15.2 torchvision 0.15.1+cu118 tqdm 4.65.0 traitlets 5.7.1 transformers 4.28.1 transforms 0.1 triton 2.0.0 typer 0.9.0 types-dataclasses 0.6.6 typing_extensions 4.5.0 tzdata 2023.3 uc-micro-py 1.0.2 urllib3 1.26.15 uvicorn 0.22.0 visualdl 2.4.2 wandb 0.15.4 wavedrom 2.0.3.post3 wcwidth 0.2.5 websockets 11.0.3 Werkzeug 2.3.6 wheel 0.38.4 wrapt 1.15.0 xxhash 3.2.0 yarl 1.9.2 zipp 3.15.0 zstandard 0.19.0
> 
> ### 运行日志或截图
> # [INFO|trainer.py:564] 2023-06-19 14:32:51,647 >> max_steps is given, it will override any value given in num_train_epochs
> [INFO|trainer.py:621] 2023-06-19 14:32:51,658 >> Using cuda_amp half precision backend
> trainable params: 569131008 || all params: 7045402624 || trainable%: 8.078048031794074
> trainable params: 569131008 || all params: 7045402624 || trainable%: 8.078048031794074
> trainable params: 569131008 || all params: 7045402624 || trainable%: 8.078048031794074
> /opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
> warnings.warn(
> trainable params: 569131008 || all params: 7045402624 || trainable%: 8.078048031794074
> /opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
> warnings.warn(
> /opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
> warnings.warn(
> /opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
> warnings.warn(
> [2023-06-19 14:32:51,761] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.9.4, git-hash=unknown, git-branch=unknown
> trainable params: 569131008 || all params: 7045402624 || trainable%: 8.078048031794074
> /opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
> warnings.warn(
> /opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
> warnings.warn(
> trainable params: 569131008 || all params: 7045402624 || trainable%: 8.078048031794074
> /opt/conda/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
> warnings.warn(
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7583 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7584 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7585 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7586 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7587 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7588 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7589 closing signal SIGTERM
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 7 (pid: 7590) of binary: /opt/conda/bin/python
> Traceback (most recent call last):
> File "/opt/conda/bin/torchrun", line 8, in
> sys.exit(main())
> File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 346, in wrapper
> return f(*args, **kwargs)
> File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
> run(args)
> File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
> elastic_launch(
> File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in **call**
> return launch_agent(self._config, self._entrypoint, list(args))
> File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
> raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> ## run_clm_sft_with_peft.py FAILED
> ## Failures:
> <NO_OTHER_FAILURES>
> # Root Cause (first observed failure):
> [0]:
> time : 2023-06-19_14:32:53
> host : 5ea5c16a9c40
> rank : 7 (local_rank: 7)
> exitcode : -9 (pid: 7590)
> error_file: <N/A>
> traceback : Signal 9 (SIGKILL) received by PID 7590
> ![dcd2f15550aa68ef9eb7abb59ad7fa3](https://user-images.githubusercontent.com/46176408/246745226-f0330430-b8fc-49e1-aba9-74488d42dac3.png)

--nproc_per_node 这个值设置1到7都可以，到8就出错，很奇怪
