### ISSUE TITLE
训练后合并模型出错

### ISSUE THREAD

**Issue by shibingli** [ymcui/Chinese-LLaMA-Alpaca#640]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

LLaMA-Plus-7B

### 操作系统

Linux

### 详细描述问题

训练完模型后，进行合并出错，无异常输出，请问各位大佬有碰到过么？

以下为操作步骤：
1、合并7B-Plus如下：
```shell
python scripts/merge_llama_with_chinese_lora.py --base_model /hd_data/aigc/LLaMA_HF/7B/ --lora_model /hd_data/aigc/Chinese-LLaMA/chinese_llama_plus_lora_7b --output_type huggingface --output_dir /hd_data/aigc/LoRA/hf/7B_Llama_Plus
```

2、执行训练任务，脚本内容如下：
```shell
bash scripts/training/run_pt.sh
```
3、run_pt.sh 内容：

```shell
lr=2e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/hd_data/aigc/LoRA/hf/7B_Llama_Plus
chinese_tokenizer_path=/hd_data/aigc/Chinese-LLaMA/chinese_llama_plus_lora_7b
dataset_dir=/hd_data/aigc/text
data_cache=/hd_data/aigc/text_cache
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=100
gradient_accumulation_steps=1
output_dir=/hd_data/aigc/text_20

deepspeed_config_file=/hd_data/aigc/Chinese-LLaMA-Alpaca/scripts/training/ds_zero2_no_offload.json

export WANDB_DISABLED=True
export use_cache=False

rm -Rf /hd_data/aigc/text_cache/*
rm -Rf /hd_data/aigc/text_20/*

torchrun --nnodes 1 --nproc_per_node 1 /hd_data/aigc/Chinese-LLaMA-Alpaca/scripts/training/run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed $RANDOM \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 500 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --gradient_checkpointing False\
    --ddp_find_unused_parameters False
```

4、合并模型(此步报错)：
```shell
python scripts/merge_llama_with_chinese_lora.py --base_model /hd_data/aigc/LoRA/hf/7B_Llama_Plus --lora_model /hd_data/aigc/text_20/pt_lora_model --output_type huggingface --output_dir /hd_data/aigc/text_lora_model
```

### 依赖情况（代码类问题务必提供）

```shell
absl-py==1.4.0
accelerate==0.20.3
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
altair==5.0.1
anyio==3.7.0
appdirs==1.4.4
async-timeout==4.0.2
attrs==23.1.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cmake==3.26.3
contourpy==1.0.7
cycler==0.11.0
datasets==2.12.0
deepspeed==0.9.4
diffusers==0.16.1
dill==0.3.6
docker-pycreds==0.4.0
exceptiongroup==1.1.1
fastapi==0.96.0
ffmpy==0.3.0
filelock==3.12.0
fire==0.5.0
flatbuffers==23.5.26
fonttools==4.39.4
frozenlist==1.3.3
fsspec==2023.5.0
ftfy==6.1.1
gitdb==4.0.10
GitPython==3.1.31
gradio==3.34.0
gradio_client==0.2.6
h11==0.14.0
hjson==3.1.0
httpcore==0.17.2
httpx==0.24.1
huggingface-hub==0.15.1
idna==3.4
importlib-metadata==6.6.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.2.0
jsonschema==4.17.3
kiwisolver==1.4.4
latex2mathml==3.76.0
linkify-it-py==2.0.2
lit==16.0.5.post0
lora-diffusion @ git+https://github.com/cloneofsimo/lora.git@bdd51b04c49fa90a88919a19850ec3b4cf3c5ecd
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.3
matplotlib==3.7.1
mdit-py-plugins==0.3.3
mdtex2html==1.2.0
mdurl==0.1.2
mediapipe==0.10.0
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.14
networkx==3.1
ninja==1.11.1
numpy==1.24.3
opencv-contrib-python==4.7.0.72
opencv-python==4.7.0.72
orjson==3.9.0
packaging==23.1
pandas==2.0.2
pathtools==0.1.2
peft==0.3.0
Pillow==9.5.0
pluggy==1.0.0
protobuf==3.20.3
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.0
pycparser==2.21
pydantic==1.10.8
pydub==0.25.1
Pygments==2.15.1
pyparsing==3.0.9
pyrsistent==0.19.3
pytest==7.3.1
python-dateutil==2.8.2
python-multipart==0.0.6
pytz==2023.3
PyYAML==6.0
regex==2023.6.3
requests==2.31.0
responses==0.18.0
safetensors==0.3.1
scikit-learn==1.2.2
scipy==1.10.1
semantic-version==2.10.0
sentencepiece==0.1.99
sentry-sdk==1.25.0
setproctitle==1.3.2
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
sounddevice==0.4.6
starlette==0.27.0
sympy==1.12
termcolor==2.3.0
threadpoolctl==3.1.0
tokenizers==0.13.3
tomli==2.0.1
toolz==0.12.0
torch==2.0.1+cu118
torchvision==0.15.2
tqdm==4.65.0
transformers @ git+https://github.com/huggingface/transformers@ba695c1efd55091e394eb59c90fb33ac3f9f0d41
triton==2.0.0
typing_extensions==4.6.3
tzdata==2023.3
uc-micro-py==1.0.2
urllib3==2.0.2
uvicorn==0.22.0
wandb==0.15.4
wcwidth==0.2.6
websockets==11.0.3
xxhash==3.2.0
yarl==1.9.2
zipp==3.15.0
```

### 运行日志或截图

```shell

(venv) root@44d8981b1556:/hd_data/aigc/Chinese-LLaMA-Alpaca# python scripts/merge_llama_with_chinese_lora.py --base_model /hd_data/aigc/LoRA/hf/7B_Llama_Plus --lora_model /hd_data/aigc/text_20/pt_lora_model --output_type huggingface --output_dir /hd_data/aigc/text
_lora_model
[2023-06-19 13:25:56,546] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Base model: /hd_data/aigc/LoRA/hf/7B_Llama_Plus
LoRA model(s) ['/hd_data/aigc/text_20/pt_lora_model']:
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.80s/it]
Peft version: 0.3.0
Loading LoRA for 7B model
Loading LoRA /hd_data/aigc/text_20/pt_lora_model...
base_model vocab size: 49953
tokenizer vocab size: 49953
Loading LoRA weights
Merging with merge_and_unload...
Traceback (most recent call last):
  File "/hd_data/aigc/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py", line 327, in <module>
    assert not torch.allclose(first_weight_old, first_weight)
AssertionError

```

**Comment by airaria** [comment]
运行run_pt.sh时用的peft版本建议换成[指定版本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/预训练脚本)

**Comment by shibingli** [comment]
@airaria   好的，我测试一下。

**Comment by shibingli** [comment]
@airaria 替换为指定版本的peft，还是一样的问题，合并7B-Plus模型时是没有问题的，操作步骤如下：
```shell
git clone https://github.com/huggingface/peft.git peft_13e53fc
cd peft_13e53fc/
git checkout 13e53fc7ee5d89d59b16523051006dddf0fb7a49
pip install -e .
```

安装好以后的版本为：

```shell
(venv) root@44d8981b1556:/hd_data/aigc/Chinese-LLaMA-Alpaca# pip list | grep peft
peft                  0.3.0.dev0   /hd_data/aigc/peft_13e53fc
```

执行合并时，出现：

```shell

(venv) root@44d8981b1556:/hd_data/aigc/Chinese-LLaMA-Alpaca# python scripts/merge_llama_with_chinese_lora.py --base_model /hd_data/aigc/LoRA/hf/7B_Llama_Plus --lora_model /hd_data/aigc/text_20/pt_lora_model --output_type huggingface --output_dir /hd_data/aigc/text_lora_model
[2023-06-20 00:00:21,886] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Base model: /hd_data/aigc/LoRA/hf/7B_Llama_Plus
LoRA model(s) ['/hd_data/aigc/text_20/pt_lora_model']:
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.51s/it]
Peft version: 0.3.0.dev0
Loading LoRA for 7B model
Loading LoRA /hd_data/aigc/text_20/pt_lora_model...
base_model vocab size: 49953
tokenizer vocab size: 49953
Loading LoRA weights
Traceback (most recent call last):
  File "/hd_data/aigc/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py", line 327, in <module>
    assert not torch.allclose(first_weight_old, first_weight)
AssertionError
(venv) root@44d8981b1556:/hd_data/aigc/Chinese-LLaMA-Alpaca#
```

**Comment by shibingli** [comment]
我看重新运行一下run_pt，试一下。

**Comment by shibingli** [comment]
@airaria   换成指定版本`peft`后，重新运行`run_pt.sh`后，再执行`merge_llama_with_chinese_lora.py`后没有问题了，感谢！
