### ISSUE TITLE
合并chinese-llama-plus-lora-7b后，继续微调chinese-alpaca-plus-lora-7b 报错 self.dtype = self.optimizer.param_groups[0]['params'][0].dtype IndexError: list index out of range

### ISSUE THREAD

**Issue by zhiyixu** [ymcui/Chinese-LLaMA-Alpaca#646]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

在合并了chinese-llama-plus-lora-7b， 按照[指令精调脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%8C%87%E4%BB%A4%E7%B2%BE%E8%B0%83%E8%84%9A%E6%9C%AC) 中的`如果想继续训练Chinese-Alpaca模型的LoRA权重`章节进行微调，报错
```bash
self.dtype = self.optimizer.param_groups[0]['params'][0].dtype 
IndexError: list index out of range
```
同时可训练参数量为0`trainable params: 0 || all params: 7045402624 || trainable%: 0.0`

run_sft.sh 文件如下：
```bash
lr=1e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/home/dashu/Documents/GPTs/models/LLaMA-7B-Plus-Merged # 这个是我用原生llama合并llama-lora-plus后的模型
chinese_tokenizer_path=/home/dashu/Documents/GPTs/models/chinese-alpaca-plus-lora-7b # 这个是我想要继续微调的lora
dataset_dir=/home/dashu/Documents/GPTs/Chinese-LLaMA-Alpaca/finetune_data # 微调的数据
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=100
gradient_accumulation_steps=1
output_dir=/home/dashu/Documents/GPTs/Chinese-LLaMA-Alpaca/lora-sd
peft_model=/home/dashu/Documents/GPTs/models/chinese-alpaca-plus-lora-7b # 想要继续微调的lora
validation_file=/home/dashu/Documents/GPTs/Chinese-LLaMA-Alpaca/viladation_data/vaildation_sd.json

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed 9878 \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 250 \
    --save_steps 500 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --peft_path ${peft_model} \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False
```
因为内存有些紧张所以按照精调wiki中的提示删除了`-modules_to_save ${modules_to_save} \`参数并修改 `peft_path`下的文件`adapter_config.json`为
```json
{
  "bias": "none",
  "enable_lora": null,
  "fan_in_fan_out": false,
  "inference_mode": true,
  "lora_alpha": 128,
  "lora_dropout": 0.05,
  "merge_weights": false,
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 64,
  "target_modules": [
    "q_proj",
    "v_proj",
    "k_proj",
    "o_proj",
    "gate_proj",
    "down_proj",
    "up_proj"
  ],
  "task_type": "CAUSAL_LM"
}
```
同时按照wiki提示删除了训练脚本中的 `--lora_rank、--lora_alpha、--lora_dropout、--trainable`和`--modules_to_save`参数

我也搜索过相关issue尝试过诸如 直接在python脚本里边把modules_to_save设置为None , 或是删除 `--gradient_checkpointing` 都没什么作用。

### 依赖情况（代码类问题务必提供）

transformers             4.28.1
peft                     0.3.0
torch                    1.13.1
deepspeed                0.9.4

### 运行日志或截图

报错如下：
```bash
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████| 2/2 [00:09<00:00,  4.94s/it]
[INFO|modeling_utils.py:3190] 2023-06-20 18:41:01,763 >> All model checkpoint weights were used when initializing LlamaForCausalLM.

[INFO|modeling_utils.py:3198] 2023-06-20 18:41:01,763 >> All the weights of LlamaForCausalLM were initialized from the model checkpoint at /home/dashu/Documents/GPTs/models/LLaMA-7B-Plus-Merged.
If your task is similar to the task the model of the checkpoint was trained on, you can already use LlamaForCausalLM for predictions without further training.
[INFO|configuration_utils.py:535] 2023-06-20 18:41:01,765 >> loading configuration file /home/dashu/Documents/GPTs/models/LLaMA-7B-Plus-Merged/generation_config.json
[INFO|configuration_utils.py:575] 2023-06-20 18:41:01,765 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "pad_token_id": 0,
  "transformers_version": "4.28.1"
}

06/20/2023 18:41:01 - INFO - __main__ - len(tokenizer):49954
06/20/2023 18:41:01 - INFO - __main__ - resize the embedding size by the size of the tokenizer
06/20/2023 18:41:12 - INFO - __main__ - Peft from pre-trained model
trainable params: 0 || all params: 7045402624 || trainable%: 0.0
06/20/2023 18:41:55 - INFO - __main__ - model.modules_to_save: None
[INFO|trainer.py:564] 2023-06-20 18:41:55,901 >> max_steps is given, it will override any value given in num_train_epochs
[INFO|trainer.py:621] 2023-06-20 18:41:55,902 >> Using cuda_amp half precision backend
/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
[2023-06-20 18:41:55,917] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.9.4, git-hash=unknown, git-branch=unknown
06/20/2023 18:41:58 - INFO - torch.distributed.distributed_c10d - Added key: store_based_barrier_key:2 to store for rank: 0
06/20/2023 18:41:58 - INFO - torch.distributed.distributed_c10d - Rank 0: Completed store-based barrier for key:store_based_barrier_key:2 with 1 nodes.
[2023-06-20 18:41:58,149] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
[2023-06-20 18:41:58,149] [INFO] [logging.py:96:log_dist] [Rank 0] Removing param_group that has no 'params' in the client Optimizer
[2023-06-20 18:41:58,149] [INFO] [logging.py:96:log_dist] [Rank 0] Using client Optimizer as basic optimizer
[2023-06-20 18:41:58,151] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Basic Optimizer = AdamW
[2023-06-20 18:41:58,151] [INFO] [utils.py:54:is_zero_supported_optimizer] Checking ZeRO support for optimizer=AdamW type=<class 'transformers.optimization.AdamW'>
[2023-06-20 18:41:58,151] [WARNING] [engine.py:1116:_do_optimizer_sanity_check] **** You are using ZeRO with an untested optimizer, proceed with caution *****
[2023-06-20 18:41:58,151] [INFO] [logging.py:96:log_dist] [Rank 0] Creating torch.float16 ZeRO stage 2 optimizer
[2023-06-20 18:41:58,152] [INFO] [stage_1_and_2.py:133:__init__] Reduce bucket size 100000000
[2023-06-20 18:41:58,152] [INFO] [stage_1_and_2.py:134:__init__] Allgather bucket size 100000000
[2023-06-20 18:41:58,152] [INFO] [stage_1_and_2.py:135:__init__] CPU Offload: False
[2023-06-20 18:41:58,152] [INFO] [stage_1_and_2.py:136:__init__] Round robin gradient partitioning: False
Using /home/dashu/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
Emitting ninja build file /home/dashu/.cache/torch_extensions/py39_cu117/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.2096266746520996 seconds
Traceback (most recent call last):
  File "/home/dashu/Documents/GPTs/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py", line 462, in <module>
    main()
  File "/home/dashu/Documents/GPTs/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py", line 424, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 309, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1185, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1420, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 271, in __init__
    self.dtype = self.optimizer.param_groups[0]['params'][0].dtype
IndexError: list index out of range
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 645637) of binary: /home/dashu/anaconda3/envs/env_finetune/bin/python
Traceback (most recent call last):
  File "/home/dashu/anaconda3/envs/env_finetune/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/dashu/anaconda3/envs/env_finetune/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm_sft_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-20_18:42:03
  host      : zhiyi
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 645637)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

**Comment by iMountTai** [comment]
因为你已经传入了`peft_model`，则可训练参数设置均以peft_model为准，adapter_config.json和adapter_model.bin是强绑定且一致的，你修改了config，则model权重理论上也应该做适当的修改

**Comment by LGY-111** [comment]
> 因为你已经传入了`peft_model`，则可训练参数设置均以peft_model为准，adapter_config.json和adapter_model.bin是强绑定且一致的，你修改了config，则model权重理论上也应该做适当的修改

可以说下具体怎么修改吗？出现了同样的问题

**Comment by zhiyixu** [comment]
@iMountTai 麻烦问下这个权重应该在哪里修改呢？

**Comment by zhiyixu** [comment]
@LGY-111 请问这个问题你解决了吗？

**Comment by iMountTai** [comment]
> @iMountTai 麻烦问下这个权重应该在哪里修改呢？

直接把你不想训练的模型权重删掉对齐config，理论上可行，但我们没试过，或者不传入`peft_model`参数，直接使用合并后的模型进行微调，这样可训练参数就可以方便控制了。

**Comment by zhiyixu** [comment]
@iMountTai 不传入peft_model 指的是我先把 chinese-llama 和 chinese-alpaca 两个lora 合并上去得到一个新的模型， 然后再来微调这个模型， 这个意思吗

**Comment by iMountTai** [comment]
@zhiyixu 是的，相关细节仔细阅读[指令精调wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%8C%87%E4%BB%A4%E7%B2%BE%E8%B0%83%E8%84%9A%E6%9C%AC)

**Comment by zhiyixu** [comment]
好的， 谢谢

**Comment by zhiyixu** [comment]
修改合并后模型的词表大小为49954后这个问题解决了

**Comment by LGY-111** [comment]
@zhiyixu 加上--peft_path还是不行。去掉并添加相应的参数就可以正常运行

**Comment by Qmymy** [comment]
> @zhiyixu 加上--peft_path还是不行。去掉并添加相应的参数就可以正常运行

如果不去掉--module_to_save传入--peft_path是可以运行的，去掉了就只能把两种lora合并后在修改config的49954才能运行

**Comment by luoyujiaye** [comment]
> 可以提供一下最终的脚本吗，我也遇到了这个问题

**Comment by Dubean** [comment]
请问之前那个报错没别的办法可以补救了吗？
