### ISSUE TITLE
多显卡推理报错

### ISSUE THREAD

**Issue by quijoo** [ymcui/Chinese-LLaMA-Alpaca#664]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型推理

### 基础模型

LLaMA-7B

### 操作系统

Windows

### 详细描述问题

使用 --gpus 0,1 参数时会这样报错，使用 --gpus 0 参数不会报错
系统：win10， 3090*2

### 运行日志或截图

(llama) D:\LLM\llama\Chinese-LLaMA-Alpaca>python scripts/openai_server_demo/openai_api_server.py --base_model D:\LLM\llama\chinese-llama-plus-13b-hf --gpus 0,1 --load_in_8bit

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:12<00:00,  4.30s/it]
Vocab of the base model: 49953
Vocab of the tokenizer: 49953
2023-06-25 17:25:27,652 - INFO - Started server process [18648]
2023-06-25 17:25:27,653 - INFO - Waiting for application startup.
2023-06-25 17:25:27,653 - INFO - Application startup complete.
2023-06-25 17:25:27,654 - INFO - Uvicorn running on http://0.0.0.0:19327 (Press CTRL+C to quit)
2023-06-25 17:25:36,509 - INFO - 127.0.0.1:52380 - "POST /v1/completions HTTP/1.1" 500
2023-06-25 17:25:36,510 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\fastapi\applications.py", line 284, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\fastapi\routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\fastapi\routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\llama\Chinese-LLaMA-Alpaca\scripts\openai_server_demo\openai_api_server.py", line 203, in create_completion
    output = predict(
             ^^^^^^^^
  File "D:\LLM\llama\Chinese-LLaMA-Alpaca\scripts\openai_server_demo\openai_api_server.py", line 139, in predict
    generation_output = model.generate(
                        ^^^^^^^^^^^^^^^
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\transformers\generation\utils.py", line 1611, in generate
    return self.beam_search(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\transformers\generation\utils.py", line 2982, in beam_search
    model_kwargs["past_key_values"] = self._reorder_cache(model_kwargs["past_key_values"], beam_idx)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 762, in _reorder_cache
    reordered_past += (tuple(past_state.index_select(0, beam_idx) for past_state in layer_past),)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DracoWorkStation\miniconda3\envs\llama\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 762, in <genexpr>
    reordered_past += (tuple(past_state.index_select(0, beam_idx) for past_state in layer_past),)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

**Comment by quijoo** [comment]
在 ubuntu 22.04 中测试也有同样的问题

**Comment by sunyuhan19981208** [comment]
``` bash
python ./scripts/openai_server_demo/openai_api_server.py --base_model /home/sunyuhan/syh/sunyuhan/zju/chinese-alpaca-plus-13b --gpus 0,1 --load_in_8bit
```
我用这个指令起的服务器程序，然后调用
```
curl http://localhost:19327/v1/completions \
>   -H "Content-Type: application/json" \
>   -d '{   
>     "prompt": "告诉我中国的首都在哪里"
>   }'
{"id":"cmpl-3AYGu5fUmurp75bHd6vmwV","object":"text_completion","created":1687788083,"model":"chinese-llama-alpaca","choices":[{"index":0,"text":"中国的首都是北京。"}]}
```
复现不出来你描述的BUG

**Comment by sunyuhan19981208** [comment]
你`pip install transformers==4.28.1`试试

**Comment by quijoo** [comment]
> 你`pip install transformers==4.28.1`试试

非常感谢，我将 transformers-4.30.0 更换为 transformers-4.28.1 后就没问题了。
