### ISSUE TITLE
预训练原版llama模型 run_pt代码有bug

### ISSUE THREAD

**Issue by zhangfan-algo** [ymcui/Chinese-LLaMA-Alpaca#681]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-33B

### 操作系统

Linux

### 详细描述问题

    model_vocab_size = model.get_output_embeddings().weight.size(0)
    if not (
       (model_vocab_size==32000 and len(tokenizer)==49953) or \
       (model_vocab_size==32000 and len(tokenizer)==32000) or \
       (model_vocab_size==49953 and len(tokenizer)==49953) or \
       (model_vocab_size==49954 and len(tokenizer)==49954)
    ):
        raise ValueError(
            f"The combination of base model (size: {model_vocab_size}) and tokenizer (size: {len(tokenizer)}) is not a valid configuration. Please check our project wiki for further information. \n"
            "Valid configurations (base model / tokenizer):\n"
            "- Continue pre-training original LLaMA: 32000 / 32000 \n"
            "- Pre-training Chinese LLaMA based on original LLaMA: 32000 / 49953 \n"
            "- Continue pre-training Chinese LLaMA: 49953 / 49953 \n"
            "- Continue pre-training Chinese Alpaca: 49954 / 49954 \n")

### 依赖情况（代码类问题务必提供）

任务默认依赖

### 运行日志或截图

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/47747764/ed5f4e39-5bed-4533-af3e-30377cf27c01)

**Comment by zhangfan-algo** [comment]
无法获取原始llama模型词表大小

**Comment by cyc00518** [comment]
我也有相同問題。

基礎模型:llama-13B-plus (基礎llama-13B與13B-plus-lora合併)

訓練代碼:
```
lr=2e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
# modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05
pretrained_model=./llama-13b-plus-hf
chinese_tokenizer_path=./llama-13b-plus-hf
dataset_dir=./pt_train
data_cache=./pt_train/cache
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=2000
gradient_accumulation_steps=1
output_dir=./train_ccp_13B_plus_pt

deepspeed_config_file=ds_zero3_no_offload.json

torchrun --nnodes 1 --nproc_per_node 2 run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed 2 \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 500 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False
```

llama-13b-plus-hf內容
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/96753147/6df935c4-ac62-4f87-981d-521df3894858)

錯誤訊息
```
Traceback (most recent call last):
  File "run_clm_pt_with_peft.py", line 759, in <module>
    main()
  File "run_clm_pt_with_peft.py", line 658, in main
    raise ValueError(
ValueError: The combination of base model (size: 0) and tokenizer (size: 49954) is not a valid configuration. Please check our project wiki for further information. 
Valid configurations (base model / tokenizer):
- Continue pre-training original LLaMA: 32000 / 32000 
- Pre-training Chinese LLaMA based on original LLaMA: 32000 / 49953 
- Continue pre-training Chinese LLaMA: 49953 / 49953 
- Continue pre-training Chinese Alpaca: 49954 / 49954
```

**Comment by airaria** [comment]
我们之前没遇到过这种情况，是不是zero3的问题？尝试下：
1. 换成zero2是否报错？
2. pull最新代码

另外请提供
* transformers、peft、pytorch版本
* 运行run_clm_pt_with_peft.py日志
* 合并模型的日志

**Comment by cyc00518** [comment]
@airaria 
1. zero2 我沒辦法跑起來 , 所以暫時沒辦法測試
2. 已經是使用最新代碼
3. 若把model_vocab_size和len(tokenizer)檢查那段註解掉,是可以利用stage3成功預訓練的
4. 我有先將合併後Chinese-llama-7b-plus的config中的vocab_size自己修正為49953再進行預訓練, 此動作是否必要?

謝謝您!

### transformers、peft、pytorch版本
```
Package                       Version
----------------------------- ------------------------
torch                         1.13.1
transformers                  4.30.0
peft                          0.3.0.dev0
```

### run_clm_pt_with_peft.py日誌
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/cuda/compat/lib'), PosixPath('/usr/local/nvidia/lib64')}
  warn(msg)
/home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /opt/conda/lib/python3.8/site-packages/torch/lib:/opt/conda/lib/python3.8/site-packages/torch_tensorrt/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
[2023-07-01 12:57:17,255] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/cuda/compat/lib'), PosixPath('/usr/local/nvidia/lib64')}
  warn(msg)
/home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /opt/conda/lib/python3.8/site-packages/torch/lib:/opt/conda/lib/python3.8/site-packages/torch_tensorrt/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
/home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//10.62.11.62'), PosixPath('8080'), PosixPath('http')}
  warn(msg)
/home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('Asia/Taipei')}
  warn(msg)
/home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/torchelastic_bvzo15sl/none_53a5mmpi/attempt_0/1/error.json')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
07/01/2023 12:57:17 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: True
[INFO|configuration_utils.py:667] 2023-07-01 12:57:17,718 >> loading configuration file ../../llama-7b-plus-hf/config.json
[INFO|configuration_utils.py:725] 2023-07-01 12:57:17,721 >> Model config LlamaConfig {
  "_name_or_path": "../../llama-7b-plus-hf",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 2048,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-06,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.30.0",
  "use_cache": true,
  "vocab_size": 49953
}

[INFO|tokenization_utils_base.py:1821] 2023-07-01 12:57:17,721 >> loading file tokenizer.model
[INFO|tokenization_utils_base.py:1821] 2023-07-01 12:57:17,721 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1821] 2023-07-01 12:57:17,721 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1821] 2023-07-01 12:57:17,722 >> loading file tokenizer_config.json
/home/appuser/.local/lib/python3.8/site-packages/datasets/dataset_dict.py:1241: FutureWarning: 'fs' was is deprecated in favor of 'storage_options' in version 2.8.0 and will be removed in 3.0.0.
You can remove this warning by passing 'storage_options=fs.storage_options' instead.
  warnings.warn(
07/01/2023 12:57:17 - INFO - __main__ - training datasets-017 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-009 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-010 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-024 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-006 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-summary_001 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-002 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-005 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-008 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-019 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-004 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-summary_007 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-DD has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-003 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-DD_TW has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-CC has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-021 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-CC_TW has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-012 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-022 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-011 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-020 has been loaded from disk
07/01/2023 12:57:17 - INFO - __main__ - training datasets-023 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-summary_009 has been loaded from disk
07/01/2023 12:57:18 - WARNING - __main__ - Process rank: 1, device: cuda:1, n_gpu: 1distributed training: True, 16-bits training: True
07/01/2023 12:57:18 - INFO - __main__ - training datasets-summary_005 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-007 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-013 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-014 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-summary_010 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-018 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-summary_008 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-summary_004 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-summary_011 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-016 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-015 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-summary_006 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-summary_003 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-summary_002 has been loaded from disk
07/01/2023 12:57:18 - INFO - __main__ - training datasets-001 has been loaded from disk
07/01/2023 12:57:18 - INFO - datasets.arrow_dataset - Caching indices mapping at /usr/src/app/Chinese-LLaMA-Alpaca/scripts/training/pt_train/cache/017/train/cache-249b064aa625acba.arrow
/home/appuser/.local/lib/python3.8/site-packages/datasets/dataset_dict.py:1241: FutureWarning: 'fs' was is deprecated in favor of 'storage_options' in version 2.8.0 and will be removed in 3.0.0.
You can remove this warning by passing 'storage_options=fs.storage_options' instead.
  warnings.warn(
07/01/2023 12:57:20 - INFO - __main__ - Num train_samples  261
07/01/2023 12:57:20 - INFO - __main__ - training example:
07/01/2023 12:57:20 - INFO - __main__ - <s> DSSSS<s> 1.產品規格 (PRODUCT SPECIFICATIONS)：<s>    - 檢驗方法：DCC方法<s>   - 固形份：最少55%
[INFO|modeling_utils.py:2575] 2023-07-01 12:57:20,111 >> loading weights file ../../llama-7b-plus-hf/pytorch_model.bin.index.json
[INFO|modeling_utils.py:1173] 2023-07-01 12:57:20,111 >> Instantiating LlamaForCausalLM model under default dtype torch.float16.
[INFO|modeling_utils.py:2669] 2023-07-01 12:57:20,112 >> Detected DeepSpeed ZeRO-3: activating zero.init() for this model
[INFO|configuration_utils.py:577] 2023-07-01 12:57:20,124 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "pad_token_id": 0,
  "transformers_version": "4.30.0"
}

[2023-07-01 12:57:27,011] [INFO] [partition_parameters.py:415:__exit__] finished initializing model with 6.89B parameters
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:22<00:00, 11.11s/it]
Linear(in_features=4096, out_features=49953, bias=False)
Traceback (most recent call last):
  File "run_clm_pt_with_peft.py", line 761, in <module>
    main()
  File "run_clm_pt_with_peft.py", line 660, in main
    raise ValueError(
ValueError: The combination of base model (size: 0) and tokenizer (size: 49953) is not a valid configuration. Please check our project wiki for further information. 
Valid configurations (base model / tokenizer):
- Continue pre-training original LLaMA: 32000 / 32000 
- Pre-training Chinese LLaMA based on original LLaMA: 32000 / 49953 
- Continue pre-training Chinese LLaMA: 49953 / 49953 
- Continue pre-training Chinese Alpaca: 49954 / 49954 

Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:22<00:00, 11.14s/it]
[INFO|modeling_utils.py:3295] 2023-07-01 12:57:49,339 >> All model checkpoint weights were used when initializing LlamaForCausalLM.

[INFO|modeling_utils.py:3303] 2023-07-01 12:57:49,339 >> All the weights of LlamaForCausalLM were initialized from the model checkpoint at ../../llama-7b-plus-hf.
If your task is similar to the task the model of the checkpoint was trained on, you can already use LlamaForCausalLM for predictions without further training.
[INFO|configuration_utils.py:537] 2023-07-01 12:57:49,342 >> loading configuration file ../../llama-7b-plus-hf/generation_config.json
[INFO|configuration_utils.py:577] 2023-07-01 12:57:49,342 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "pad_token_id": 0,
  "transformers_version": "4.30.0"
}

Traceback (most recent call last):
  File "run_clm_pt_with_peft.py", line 761, in <module>
    main()
  File "run_clm_pt_with_peft.py", line 660, in main
    raise ValueError(
ValueError: The combination of base model (size: 0) and tokenizer (size: 49953) is not a valid configuration. Please check our project wiki for further information. 
Valid configurations (base model / tokenizer):
- Continue pre-training original LLaMA: 32000 / 32000 
- Pre-training Chinese LLaMA based on original LLaMA: 32000 / 49953 
- Continue pre-training Chinese LLaMA: 49953 / 49953 
- Continue pre-training Chinese Alpaca: 49954 / 49954 

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 13918 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 13919) of binary: /opt/conda/bin/python3.8
Traceback (most recent call last):
  File "/home/appuser/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/appuser/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/appuser/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/appuser/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/appuser/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/appuser/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm_pt_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-01_12:57:52
  host      : ai_test.ccpgp.com
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 13919)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

若我在出錯程式碼前先print,看起來詞表確實是49953

` print(f"{model.get_output_embeddings()}")` 
```
Linear(in_features=4096, out_features=49953, bias=False)
```

### 合併日誌
`python merge_llama_with_chinese_lora_low_mem.py --base_model 'elinas/llama-7b-hf-transformers-4.29' --lora_model 'ziqingyang/chinese-llama-plus-lora-7b' --output_type huggingface --output_dir llama-7b-plus-hf`
```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/cuda/compat/lib')}
  warn(msg)
/home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /opt/conda/lib/python3.8/site-packages/torch/lib:/opt/conda/lib/python3.8/site-packages/torch_tensorrt/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
/home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('Asia/Taipei')}
  warn(msg)
/home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('http'), PosixPath('8080'), PosixPath('//10.62.11.62')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/appuser/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Base model: elinas/llama-7b-hf-transformers-4.29
LoRA model(s) ['ziqingyang/chinese-llama-plus-lora-7b']:
Loading ziqingyang/chinese-llama-plus-lora-7b
Cannot find lora model on the disk. Downloading lora model from hub...
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 166/166 [00:00<00:00, 18.5kB/s]
Downloading (…)/adapter_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 420/420 [00:00<00:00, 42.3kB/s]
Downloading (…)8cb24/.gitattributes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.48k/1.48k [00:00<00:00, 133kB/s]
Downloading (…)12bf38cb24/README.md: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 320/320 [00:00<00:00, 27.3kB/s]
Downloading (…)cial_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72.0/72.0 [00:00<00:00, 7.63kB/s]
Downloading tokenizer.model: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 758k/758k [00:00<00:00, 16.7MB/s]
Downloading adapter_model.bin: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 858M/858M [00:10<00:00, 84.3MB/s]
Fetching 7 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:11<00:00,  1.61s/it]
Cannot find lora model on the disk. Downloading lora model from hub...
Downloading (…)fdb7a/.gitattributes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.48k/1.48k [00:00<00:00, 671kB/s]
Downloading (…)a55fdb7a/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 507/507 [00:00<00:00, 231kB/s]
Downloading (…)82a55fdb7a/README.md: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8.34k/8.34k [00:00<00:00, 3.65MB/s]
Downloading (…)neration_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 137/137 [00:00<00:00, 66.8kB/s]
Downloading (…)model.bin.index.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26.8k/26.8k [00:00<00:00, 2.52MB/s]
Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 411/411 [00:00<00:00, 36.1kB/s]
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 727/727 [00:00<00:00, 329kB/s]
Downloading (…)fdb7a/tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 2.07MB/s]
Downloading tokenizer.model: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 685kB/s]
Downloading (…)l-00002-of-00002.bin: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.50G/3.50G [01:06<00:00, 52.2MB/s]
Downloading (…)l-00001-of-00002.bin: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.98G/9.98G [02:28<00:00, 67.2MB/s]
Fetching 11 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [02:29<00:00, 13.62s/it]
Loading ckpt pytorch_model-00001-of-00002.bin███████████████████████████████████████████▍                                                                                      | 3.48G/9.98G [01:06<02:05, 51.6MB/s]
Merging...g (…)l-00001-of-00002.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 9.97G/9.98G [02:28<00:00, 80.1MB/s]
Saving ckpt pytorch_model-00001-of-00002.bin to llama-7b-plus-hf in HF format...
Loading ckpt pytorch_model-00002-of-00002.bin
Merging...
Saving ckpt pytorch_model-00002-of-00002.bin to llama-7b-plus-hf in HF format...
Saving tokenizer
Saving config.json
Saving generation_config.json
Saving pytorch_model.bin.index.json
Done.
```

**Comment by airaria** [comment]
@zhangfan-algo @cyc00518 看起来是zero3的问题 https://github.com/huggingface/transformers/issues/23019
如果能确保模型词表大小和tokenizer匹配，可以先把那段assert注释掉。

> 我有先將合併後Chinese-llama-7b-plus的config中的vocab_size自己修正為49953再進行預訓練, 此動作是否必要?

这个确实修改，我们之后会修复此问题。
