### ISSUE TITLE
local_rank pid

### ISSUE THREAD

**Issue by 0xZoomEye** [ymcui/Chinese-LLaMA-Alpaca#689]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-Plus-7B

### 操作系统

Linux

### 详细描述问题

使用单节点单进程, 执行模型精调的时候报如下错误

### 运行日志或截图

```
[2023-06-29 18:27:50,910] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-06-29 18:27:52,934] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2023-06-29 18:27:52,934] [INFO] [comm.py:594:init_distributed] cdb=None
[2023-06-29 18:27:52,934] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
06/29/2023 18:27:55 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: True
[INFO|configuration_utils.py:666] 2023-06-29 18:27:55,700 >> loading configuration file /home/kslab/Desktop/models/7B_full_model_hf/config.json
[INFO|configuration_utils.py:720] 2023-06-29 18:27:55,701 >> Model config LlamaConfig {
  "_name_or_path": "/home/kslab/Desktop/models/7B_full_model_hf",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 2048,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-06,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.28.1",
  "use_cache": true,
  "vocab_size": 49954
}

[INFO|tokenization_utils_base.py:1807] 2023-06-29 18:27:55,701 >> loading file tokenizer.model
[INFO|tokenization_utils_base.py:1807] 2023-06-29 18:27:55,701 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1807] 2023-06-29 18:27:55,701 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1807] 2023-06-29 18:27:55,701 >> loading file tokenizer_config.json
06/29/2023 18:27:55 - INFO - __main__ - training files: /home/kslab/Desktop/Chinese-LLaMA-Alpaca/data/test.json
06/29/2023 18:27:55 - WARNING - root - building dataset...
06/29/2023 18:27:55 - INFO - __name__ - training datasets-/home/kslab/Desktop/Chinese-LLaMA-Alpaca/data/test.json has been loaded from disk
06/29/2023 18:27:55 - INFO - __main__ - Num train_samples  1999
06/29/2023 18:27:55 - INFO - __main__ - training example:
06/29/2023 18:27:55 - INFO - __main__ - <s> Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
用更简短、更简单的方式改述给定的段落。
贫乏的饮食对健康的影响不仅仅局限于肥胖的风险，还可能导致缺乏、维生素和矿物质流失以及更容易患病。

### Response:  贫乏的饮食可能通过引起肥胖、缺乏、维生素/矿物质流失和疾病易感性来危害健康。</s>
Traceback (most recent call last):
  File "/home/kslab/Desktop/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py", line 472, in <module>
    main()
  File "/home/kslab/Desktop/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py", line 334, in main
    logger.info(f"training files: {' '.join(files)}")
TypeError: sequence item 0: expected str instance, NoneType found
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2960) of binary: /home/kslab/anaconda3/envs/llama/bin/python
Traceback (most recent call last):
  File "/home/kslab/anaconda3/envs/llama/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/kslab/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/kslab/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/kslab/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/kslab/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kslab/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm_sft_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-29_18:27:59
  host      : kslab-tower
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2960)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
run_sft.sh: 58: --torch_dtype: not found
run_sft.sh: 62: --ddp_find_unused_parameters: not found

```

**Comment by airaria** [comment]
请提供运行的sh脚本
