### ISSUE TITLE
13B模型合并SHA256不一致，指令精调报错

### ISSUE THREAD

**Issue by slxy-hub** [ymcui/Chinese-LLaMA-Alpaca#709]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

```
您好，我合并Chinese-Alpaca-Plus-13B pth版本后，对照sha256.md不一致，经检查，前面的13B-hf、13B-llama-plus-lora、13B-alpaca-plus-lora、tokeniser.model 的SHA256是一致的。
其中:
1. merge_llama_with_chinese_lora_low_mem.py和merge_llama_with_chinese_lora.py两种方式都运行过，sha256结果都对不上
2. 同样的方式7B合并以及后续精调没有问题
3. 考虑可能会存在一些机器特定的计算误差的问题，忽略不一致，进一步对13B合并后的模型做精调，精调过程依然报错

请问是否还是合并模型出现的问题?


```

### 依赖情况（代码类问题务必提供）

```
peft               0.3.0.dev0
torch              2.0.1+cu118
torchaudio         2.0.2+cu118
torchvision        0.15.2+cu118
transformers       4.28.1
```

### 运行日志或截图

```
**sha256:**
04bbf444b996b2d514f0041e07e9ce3599624153b6caad6c2c2c509cdddf4379  consolidated.00.pth
3bb84053c3b476331f3bcf07d6ca6b32ce66f34f76625b7bb162a414d8d19857  consolidated.01.pth


**13B合并代码：**
python scripts/merge_llama_with_chinese_lora.py \
--base_model all_models/llama_models_13B/13B_hf/ \
--lora_model all_models/lora_model/chinese_llama_plus_lora_13b,all_models/lora_model/chinese_alpaca_plus_lora_13b \
--output_type pth \
--output_dir all_models/llama_models_13B/13B_full_model_pth

**13B合并后精调报错：**
Traceback (most recent call last):
  File "/home/gistrans2/data/Chinese-LLaMA-Alpaca-main/scripts/training/run_clm_sft_with_peft.py", line 462, in <module>
    main()
  File "/home/gistrans2/data/Chinese-LLaMA-Alpaca-main/scripts/training/run_clm_sft_with_peft.py", line 377, in main
    model = PeftModel.from_pretrained(model, training_args.peft_path)
  File "/home/gistrans2/anaconda3/envs/ch-llama-alpaca/lib/python3.9/site-packages/peft/peft_model.py", line 161, in from_pretrained
    model = set_peft_model_state_dict(model, adapters_weights)
  File "/home/gistrans2/anaconda3/envs/ch-llama-alpaca/lib/python3.9/site-packages/peft/utils/save_and_load.py", line 74, in set_peft_model_state_dict
    model.load_state_dict(peft_model_state_dict, strict=False)
  File "/home/gistrans2/anaconda3/envs/ch-llama-alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
	size mismatch for base_model.model.model.embed_tokens.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([49954, 5120]).
	size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_A.weight: copying a param with shape torch.Size([64, 4096]) from checkpoint, the shape in current model is torch.Size([64, 5120]).
	size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_B.weight: copying a param with shape torch.Size([4096, 64]) from checkpoint, the shape in current model is torch.Size([5120, 64]).
	size mismatch for base_model.model.model.layers.0.self_attn.k_proj.lora_A.weight: copying a param with shape torch.Size([64, 4096]) from checkpoint, the shape in current model is torch.Size([64, 5120]).
	size mismatch for base_model.model.model.layers.0.self_attn.k_proj.lora_B.weight: copying a param with shape torch.Size([4096, 64]) from checkpoint, the shape in current model is torch.Size([5120, 64]).

```

**Comment by airaria** [comment]
从13B合并后精调的报错信息看你精调时加载的LoRA是7B模型的lora

**Comment by slxy-hub** [comment]
> 从13B合并后精调的报错信息看你精调时加载的LoRA是7B模型的lora

感谢您的回复！检查了一下确实是没注意到这里写错了，非常感谢！
