### ISSUE TITLE
OSError: ziqingyang/chinese-llama-plus-lora-7b does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by tanshuai** [ymcui/Chinese-LLaMA-Alpaca#738]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型推理

### 基础模型

LLaMA-Plus-7B

### 操作系统

Linux

### 详细描述问题

使用Transformers从HuggingFace加载模型，遇到错误：

Entry Not Found for url: https://huggingface.co/ziqingyang/chinese-llama-plus-lora-7b/resolve/main/config.json.

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
Traceback (most recent call last):
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/ziqingyang/chinese-llama-plus-lora-7b/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1541, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-64adaaf4-2ad96fe858d145d55d5ec718;a3dd5ffa-f978-4131-bf12-d8dfdce0be48)

Entry Not Found for url: https://huggingface.co/ziqingyang/chinese-llama-plus-lora-7b/resolve/main/config.json.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/d_001/gptchain/basaran/basaran/__main__.py", line 41, in <module>
    stream_model = load_model(
  File "/data/d_001/gptchain/basaran/basaran/model.py", line 342, in load_model
    model = AutoModelForCausalLM.from_pretrained(name_or_path, **kwargs)
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 456, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 944, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/anaconda3/envs/cuda_test2/lib/python3.9/site-packages/transformers/utils/hub.py", line 463, in cached_file
    raise EnvironmentError(
OSError: ziqingyang/chinese-llama-plus-lora-7b does not appear to have a file named config.json. Checkout 'https://huggingface.co/ziqingyang/chinese-llama-plus-lora-7b/main' for
available files.
```

**Comment by airaria** [comment]
请提供完整的代码上下文？
