### ISSUE TITLE
执行 inference_hf.py 时提示缺少文件

### ISSUE THREAD

**Issue by XXXG00W0** [ymcui/Chinese-LLaMA-Alpaca#747]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型推理

### 基础模型

Alpaca-Plus-7B

### 操作系统

Windows

### 详细描述问题

在使用`inference_hf.py`推理时，遇到错误提示我没有`pytorch_model.bin`, `tf_model.h5`, `model.ckpt.index` 或 `flax_model.msgpack`，但是从一开始下载LLaMA的模型时，就没有这些文件，后续的转换、合并操作也未生成这些文件，想问问这种情况，要怎么处理呢：
* LLaMA模型不是从meta那边获取的，申请了获取模型但是一直没消息，所以我先用了别人私传的模型 
```powershell
PS D:\Chinese-LLaMA-Alpaca\Chinese-LLaMA-Alpaca\scripts\inference> python310 .\inference_hf.py --base_model D:\Chinese-LLaMA-Alpaca\llama.cpp\zh-models\7B --with_prompt --data_file D:\Chinese-LLaMA-Alpaca\llama.cpp\prompts\alpaca.txt --predictions_file .\out.txt --tokenizer_path D:\Chinese-LLaMA-Alpaca\llama.cpp\zh-models\
Traceback (most recent call last):
  File "D:\Chinese-LLaMA-Alpaca\Chinese-LLaMA-Alpaca\scripts\inference\inference_hf.py", line 92, in <module>
    base_model = LlamaForCausalLM.from_pretrained(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2405, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory D:\Chinese-LLaMA-Alpaca\llama.cpp\zh-models\7B.
```
使用的模型是`Alpaca-Plus-7B`, `--base_model`的路径下的内容有:
```powershell
PS D:\Chinese-LLaMA-Alpaca\llama.cpp\zh-models> ls


    目录: D:\Chinese-LLaMA-Alpaca\llama.cpp\zh-models


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2023/7/15     16:25                7B
-a----         2023/7/15     11:15    13771083975 consolidated.00.pth
-a----         2023/7/15     11:13            102 special_tokens_map.json
-a----         2023/7/15     11:13         757972 tokenizer.model
-a----         2023/7/15     11:13            760 tokenizer_config.json
-a----         2023/7/15     16:25            321 各个文件解释.txt 
```
其中`zh-models\7B`文件夹的内容有:
```powershell
PS D:\Chinese-LLaMA-Alpaca\llama.cpp\zh-models\7b> ls


    目录: D:\Chinese-LLaMA-Alpaca\llama.cpp\zh-models\7b


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2023/7/14     14:37            524 config.json
-a----         2023/7/15     11:19    13772213056 ggml-model-f16.bin
-a----         2023/7/15     11:47     5165677376 ggml-model-q5_1.bin
-a----         2023/7/15     11:13            101 params.json
```

整个项目的文件结构如下:
 ```powershell
PS D:\Chinese-LLaMA-Alpaca> ls


    目录: D:\Chinese-LLaMA-Alpaca


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2023/7/15     14:33                .idea
d-----         2023/7/14     15:29                .ipynb_checkpoints
d-----         2023/7/15     16:54                Chinese-LLaMA-Alpaca
d-----         2023/7/14     17:30                chinese_alpaca_plus_lora_7b
d-----         2023/7/14     17:11                chinese_llama_plus_lora_7b
d-----         2023/7/14     13:54                LLaMA-original-model
d-----         2023/7/15     10:52                llama.cpp
d-----         2023/7/11     16:39                OpenBLAS-0.3.23-x64
d-----         2023/7/15      9:55                OpenBLAS-0.3.23-x64 (1)
d-----         2023/7/15     15:13                test
d-----         2023/7/15     14:29                transformers
d-----         2023/7/14     17:41                w64devkit-fortran-1.19.0
d-----         2023/7/15     15:53                模型备份                                                              
-a----         2023/7/15     16:43          39661 Chinese_LLaMA_Alpaca.ipynb
```

### 依赖情况（代码类问题务必提供）

```bash
$ pip310 list | grep -E 'transformers|peft|torch'
peft               0.3.0
torch              1.13.1
transformers       4.28.1
```

### 运行日志或截图

合并后的`consolidated.00.pth`文件的sha256值与<a href=https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md>llama.cpp量化部署</a>提供的值是一致的, 利用`llama.cpp`推理也能正常的运行:
```powershell
PS D:\Chinese-LLaMA-Alpaca\llama.cpp> ./main -m zh-models/7B/ggml-model-q5_1.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.1 -b 8 -t 6
main: build = 831 (27ad57a)
main: seed  = 1689393361
llama.cpp: loading model from zh-models/7B/ggml-model-q5_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 49954
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 9 (mostly Q5_1)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: mem required  = 6717.79 MB (+ 1026.00 MB per state)
llama_new_context_with_model: kv self size  = 1024.00 MB

system_info: n_threads = 6 / 12 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
main: interactive mode on.
Reverse prompt: '### Instruction:

'
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.200000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 2048, n_batch = 8, n_predict = 256, n_keep = 149


== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

 Below is an instruction that describes a task. Write a response in Chinese that appropriately completes the request.
《原神》是由上海米哈游网络科技股份有限公司制作发行的一款开放世界冒险游戏，游戏发生在一个被称作“提瓦特”的幻想世界，在这里，被神选中的人将被授予“神之眼”，导引元素之力。玩家将扮演一位名为“旅行者”的神秘角色，在自由的旅行中邂逅性格各异、能力独特的同伴们，和他们一起击败强敌，找回失散的亲人——同时，逐步发掘“原神”的真相。请为《原神》写一段约100字的推广文章。
> Below is an instruction that describes a task. Write a response in Chinese that appropriately completes the request.《原神》是由上海米哈游网络科技股份有限公司制作发行的一款开放世界冒险游戏，游戏发生在一个被称作"提瓦特"的幻想世界，在这里，被神选中的人将被授予"神之眼"，导引元素之力。玩家将扮演一位名为"旅行者"的神秘角色，在自由的旅行中邂逅性格各异、能力独特的同伴们，和他们一起击败强敌，找回失散的亲人--同时，逐步发掘"原神"的真相。请为《原神》写一段约100字的推广文章。
《原神》是一款开放世界冒险游戏，玩家将扮演一位名为“旅行者”的神秘角色，在自由的旅行中邂逅性格各异、能力独特的同伴们，和他们一起击败强敌，找回失散的亲人--同时，逐步发掘"原神"的真相。游戏中，玩家可以探索各种不同的场景和任务，并与NPC和其他玩家 互动。游戏画面精美，音乐动听，操作简单易上手，适合所有年龄段的玩家。如果你喜欢冒险、
>
解谜和自由度高的游戏，那么《原神》一定不容错过！
```

**Comment by airaria** [comment]
`inference_hf.py`不能加载ggml或pth格式的模型文件，只能加载hf格式的模型。

**Comment by XXXG00W0** [comment]
您好，谢谢您的回复。我把模型转换成hf格式了，现在运行的错误是这样的：
```powershell
PS D:\Chinese-LLaMA-Alpaca\Chinese-LLaMA-Alpaca\scripts\inference> python310 .\inference_hf.py --base_model D:\Chinese-LLaMA-Alpaca\Chinese-Alpaca-hugging-face\ --with_prompt --data_file D:\Chinese-LLaMA-Alpaca\llama.cpp\prompts\alpaca.txt --predictions_file .\out.txt --tokenizer_path D:\Chinese-LLaMA-Alpaca\llama.cpp\zh-models\
Traceback (most recent call last):
  File "D:\Chinese-LLaMA-Alpaca\Chinese-LLaMA-Alpaca\scripts\inference\inference_hf.py", line 92, in <module>
    base_model = LlamaForCausalLM.from_pretrained(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2795, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2889, in _load_pretrained_model
    raise ValueError(
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.
```

**Comment by XXXG00W0** [comment]
这是转换hf的运行日志：
```bash
Administrator@DESKTOP-OSH296I MINGW64 ~/AppData/Local/Programs/Python/Python310/Lib/site-packages/transformers/models/llama
$ python310 convert_llama_weights_to_hf.py --input_dir D:\\Chinese-LLaMA-Alpaca\\llama.cpp\\zh-models --model_size 7B --output_dir D:\\Chinese-LLaMA-Alpaca\\Chinese-Alpaca-hugging-face
Fetching all parameters from the checkpoint at D:\Chinese-LLaMA-Alpaca\llama.cpp\zh-models\7B.
Loading the checkpoint in a Llama model.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
Saving in the Transformers format.
Saving a {tokenizer_class} to {tokenizer_path}
```

**Comment by airaria** [comment]
> 您好，谢谢您的回复。我把模型转换成hf格式了，现在运行的错误是这样的：
> 
> ```powershell
> PS D:\Chinese-LLaMA-Alpaca\Chinese-LLaMA-Alpaca\scripts\inference> python310 .\inference_hf.py --base_model D:\Chinese-LLaMA-Alpaca\Chinese-Alpaca-hugging-face\ --with_prompt --data_file D:\Chinese-LLaMA-Alpaca\llama.cpp\prompts\alpaca.txt --predictions_file .\out.txt --tokenizer_path D:\Chinese-LLaMA-Alpaca\llama.cpp\zh-models\
> Traceback (most recent call last):
>   File "D:\Chinese-LLaMA-Alpaca\Chinese-LLaMA-Alpaca\scripts\inference\inference_hf.py", line 92, in <module>
>     base_model = LlamaForCausalLM.from_pretrained(
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2795, in from_pretrained
>     ) = cls._load_pretrained_model(
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2889, in _load_pretrained_model
>     raise ValueError(
> ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.
> ```

显卡配置是多少？可能是显存不足，加上`--only_cpu`参数启动试试

**Comment by XXXG00W0** [comment]
您好，我是用cpu运行的，加上`--only_cpu`的结果后，错误还是一样的：
```shell
PS D:\Chinese-LLaMA-Alpaca\Chinese-LLaMA-Alpaca\scripts\inference> python310 .\inference_hf.py --base_model D:\Chinese-LLaMA-Alpaca\Chinese-Alpaca-hugging-face\ --with_prompt --data_file D:\Chinese-LLaMA-Alpaca\llama.cpp\prompts\alpaca.txt --predictions_file .\out.txt --tokenizer_path D:\Chinese-LLaMA-Alpaca\llama.cpp\zh-models\ --only_cpu
```
```python
Traceback (most recent call last):
File "D:\Chinese-LLaMA-Alpaca\Chinese-LLaMA-Alpaca\scripts\inference\inference_hf.py", line 92, in <module>
base_model = LlamaForCausalLM.from_pretrained(
    File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2795, in from_pretrained
) = cls._load_pretrained_model(
    File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2889, in _load_pretrained_model
raise ValueError(
    ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.
```
这是现在推理使用的cpu：

	AMD Ryzen 5 5600X 6-Core Processor 

	基准速度:	3.70 GHz
	插槽:	1
	内核:	6
	逻辑处理器:	12
	虚拟化:	已启用
	L1 缓存:	384 KB
	L2 缓存:	3.0 MB
	L3 缓存:	32.0 MB

	利用率	2%
	速度	4.04 GHz
	正常运行时间	0:00:10:24
	进程	226
	线程	3096
	句柄	108495

**Comment by ymcui** [comment]
你的内存有多大？一般是内存不够了才会offload到磁盘。

**Comment by XXXG00W0** [comment]
您好，内存是16GB，我试试关闭其他的程序，再运行一次

**Comment by XXXG00W0** [comment]
关闭其他程序后，内存情况如下，错误还是刚刚的错误：

	16.0 GB

	速度:	2133 MHz
	已使用的插槽:	1/4
	外形规格:	DIMM
	为硬件保留的内存:	49.1 MB

	可用	10.9 GB
	已缓存	6.9 GB
	已提交	7.3/26.0 GB
	分页缓冲池	681 MB
	非分页缓冲池	453 MB
	使用中(已压缩)	5.0 GB (0 MB)

**Comment by ymcui** [comment]
你的内存是不够的。7B模型在FP16精度下就已经13G左右了。你需要使用8bit形式进行加载（需要安装bitsandbytes包）。

https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/b64ef25ca92aa6b196b71f06b35e048113544967/scripts/inference/inference_hf.py#L94C22-L94C27
脚本里的这一行改为True之后重新运行命令

**Comment by XXXG00W0** [comment]
感谢您提供的这些资料，我安装了bitsandbytes包，遇到以下问题：
```powershell
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Traceback (most recent call last):
  File "D:\Chinese-LLaMA-Alpaca\Chinese-LLaMA-Alpaca\scripts\inference\inference_hf.py", line 92, in <module>
    base_model = LlamaForCausalLM.from_pretrained(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2740, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.
```
我猜测问题是因为，我的显卡不是NVIDIA的，不支持CUDA（AMD Radeon RX 6600 XT），因此bitsandbytes并不能支持GPU的8-bit量化等操作。然后查阅huggingface提供的<a href=https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu>链接</a>，发现huggingface并未支持在cpu上使用8bit精度：(如果我没有搞错英文的意思的话）
<quote><i>Note that the weights that will be dispatched on CPU will not be converted in 8-bit, thus kept in float32.</i></quote>
这样是不是意味着，这个问题只能下面两种方式来解决呢：
1. 添加更多的内存
2. 更换一张NVIDIA的显卡

**Comment by ymcui** [comment]
是的，如果你一定要使用huggingface来做inference的话，主要就是你列举的两条办法。
llama.cpp是比较推荐的使用方式，且可以通过clblast支持AMD显卡做推理。
需要重新编译llama.cpp（记得先make clean）：https://github.com/ggerganov/llama.cpp#clblast

**Comment by XXXG00W0** [comment]
我明白了，非常感谢您和[airaria](https://github.com/airaria)的帮助，谢谢大佬们~
