### ISSUE TITLE
训练中报错Unable to concatenate an empty list of datasets.main()

### ISSUE THREAD

**Issue by DRZJ1** [ymcui/Chinese-LLaMA-Alpaca#759]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-Plus-13B

### 操作系统

Linux

### 详细描述问题

CUDA_VISIBLE_DEVICES=0,1,2,3
torchrun --nnodes 1 --nproc_per_node 4 /home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py \
    --model_name_or_path /home/ubuntu/llama-plus \
    --tokenizer_name_or_path /home/ubuntu/chinese-alpaca-plus-lora-13b \
    --dataset_dir /home/ubuntu/Chinese-LLaMA-Alpaca/data/alpaca_data_zh_51k.json \
    --peft_path /home/ubuntu/chinese-alpaca-plus-lora-13b \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --do_train \
    --seed $RANDOM \
    --fp16 \
    --lr_scheduler_type cosine \
    --learning_rate 1e-4 \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 250 \
    --save_steps 500 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 8 \
    --max_seq_length 512 \
    --output_dir nt-alpaca \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank 8 \
    --lora_alpha 32 \
    --trainable "q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj" \
    --modules_to_save "embed_tokens,lm_head" \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --validation_file /home/ubuntu/20230609.json \
    --peft_path /home/ubuntu/chinese-alpaca-plus-lora-13b \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```
4张3090

### 运行日志或截图

```
# 请在此处粘贴运行日志
```Traceback (most recent call last):
  File "/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py", line 441, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py", line 441, in <module>
  File "/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py", line 441, in <module>
    main()
  File "/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py", line 315, in main
    main()
  File "/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py", line 315, in main
    main()
    train_dataset = build_instruction_dataset(  File "/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py", line 315, in main

  File "/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/build_dataset.py", line 85, in build_instruction_dataset
    all_datasets = concatenate_datasets(all_datasets)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/datasets/combine.py", line 188, in concatenate_datasets
        train_dataset = build_instruction_dataset(train_dataset = build_instruction_dataset(

  File "/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/build_dataset.py", line 85, in build_instruction_dataset
  File "/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/build_dataset.py", line 85, in build_instruction_dataset
Traceback (most recent call last):
    raise ValueError("Unable to concatenate an empty list of datasets.")
      File "/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py", line 441, in <module>
all_datasets = concatenate_datasets(all_datasets)    
ValueErrorall_datasets = concatenate_datasets(all_datasets)
:   File "/home/ubuntu/.local/lib/python3.8/site-packages/datasets/combine.py", line 188, in concatenate_datasets
  File "/home/ubuntu/.local/lib/python3.8/site-packages/datasets/combine.py", line 188, in concatenate_datasets
Unable to concatenate an empty list of datasets.
    raise ValueError("Unable to concatenate an empty list of datasets.")    
raise ValueError("Unable to concatenate an empty list of datasets.")ValueError
: Unable to concatenate an empty list of datasets.
ValueError:     Unable to concatenate an empty list of datasets.main()

  File "/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py", line 315, in main
    train_dataset = build_instruction_dataset(
  File "/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/build_dataset.py", line 85, in build_instruction_dataset
    all_datasets = concatenate_datasets(all_datasets)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/datasets/combine.py", line 188, in concatenate_datasets
    raise ValueError("Unable to concatenate an empty list of datasets.")
ValueError: Unable to concatenate an empty list of datasets.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 148565) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-07-18_04:13:38
  host      : ip-172-31-72-127.ec2.internal
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 148566)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-07-18_04:13:38
  host      : ip-172-31-72-127.ec2.internal
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 148567)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-07-18_04:13:38
  host      : ip-172-31-72-127.ec2.internal
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 148568)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-18_04:13:38
  host      : ip-172-31-72-127.ec2.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 148565)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by DRZJ1** [comment]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
4.30.0
0.3.0
1.13.1+cu117

**Comment by airaria** [comment]
`--dataset_dir` 后面的参数是训练数据所在的文件夹，而不是具体的文件名

**Comment by DRZJ1** [comment]
谢谢谢谢，请问数据文件名是哪个参数？还是说来个空文件夹

**Comment by airaria** [comment]
不需要提供文件名，程序会去查找并加载`--dataset_dir`下所有以json结尾的文件作为训练数据

**Comment by Cueb-QF-Zqs** [comment]
同样有以上错误
