### ISSUE TITLE
使用langchain检索式问答输入问题后报错 电脑带有A100显卡

### ISSUE THREAD

**Issue by ai499** [ymcui/Chinese-LLaMA-Alpaca#775]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型推理

### 基础模型

LLaMA-13B

### 操作系统

Linux

### 详细描述问题

```
python3 langchain_sum.py \
  --model_path /root/7_17_alpaca \
  --file_path doc.txt \
  --chain_type refine
```

### 依赖情况（代码类问题务必提供）

accelerate               0.20.3
aiohttp                  3.8.4
aiosignal                1.3.1
anyio                    3.7.0
argilla                  1.12.1
async-timeout            4.0.2
attrs                    21.2.0
Automat                  20.2.0
backoff                  2.2.1
bcrypt                   3.2.0
beautifulsoup4           4.12.2
blinker                  1.4
certifi                  2023.5.7
cffi                     1.15.1
chardet                  4.0.0
charset-normalizer       3.1.0
chromadb                 0.3.23
click                    8.0.3
clickhouse-connect       0.6.8
cloud-init               19.1.21
cmake                    3.27.0
colorama                 0.4.4
colorclass               2.2.2
command-not-found        0.3
commonmark               0.9.1
compressed-rtf           1.0.6
configobj                5.0.8
constantly               15.1.0
cryptography             41.0.2
dataclasses-json         0.5.12
datasets                 2.13.1
dbus-python              1.2.18
decorator                4.4.2
deepspeed                0.9.5
Deprecated               1.2.14
dill                     0.3.6
diskcache                5.6.1
distro                   1.7.0
distro-info              1.1build1
duckdb                   0.8.1
easygui                  0.98.3
ebcdic                   1.1.1
et-xmlfile               1.1.0
exceptiongroup           1.1.2
extract-msg              0.41.1
faiss-cpu                1.7.4
fastapi                  0.99.1
filelock                 3.12.2
frozenlist               1.3.3
fsspec                   2023.6.0
gpt4all                  0.3.4
greenlet                 2.0.2
h11                      0.14.0
hjson                    3.1.0
hnswlib                  0.7.0
httpcore                 0.16.3
httplib2                 0.20.2
httptools                0.6.0
httpx                    0.23.3
huggingface-hub          0.15.1
hyperlink                21.0.0
idna                     3.3
IMAPClient               2.3.1
importlib-metadata       4.6.4
incremental              21.3.0
iniconfig                2.0.0
jeepney                  0.7.1
Jinja2                   3.1.2
joblib                   1.3.1
jsonpatch                1.32
jsonpointer              2.3
jsonschema               4.17.3
keyring                  23.5.0
langchain                0.0.197
langchainplus-sdk        0.0.20
langsmith                0.0.11
lark-parser              0.12.0
launchpadlib             1.10.16
lazr.restfulclient       0.14.4
lazr.uri                 1.0.6
lit                      16.0.6
llama-cpp-python         0.1.50
lxml                     4.9.3
lz4                      4.3.2
Markdown                 3.4.3
MarkupSafe               2.1.2
marshmallow              3.19.0
monotonic                1.6
more-itertools           8.10.0
mpmath                   1.3.0
msg-parser               1.2.0
msoffcrypto-tool         5.1.1
multidict                6.0.4
multiprocess             0.70.14
mypy-extensions          1.0.0
netifaces                0.11.0
networkx                 3.1
ninja                    1.11.1
nltk                     3.8.1
numexpr                  2.8.4
numpy                    1.23.5
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oauthlib                 3.2.2
olefile                  0.46
oletools                 0.60.1
openapi-schema-pydantic  1.2.4
openpyxl                 3.1.2
packaging                23.1
pandas                   1.5.3
pandoc                   2.3
pcodedmp                 1.2.6
pdfminer.six             20221105
peft                     0.3.0.dev0
pexpect                  4.8.0
Pillow                   10.0.0
pip                      22.0.2
pluggy                   1.2.0
plumbum                  1.8.2
ply                      3.11
posthog                  3.0.1
protobuf                 4.23.4
psutil                   5.9.5
ptyprocess               0.7.0
py-cpuinfo               9.0.0
pyarrow                  12.0.1
pyasn1                   0.4.8
pyasn1-modules           0.2.1
pycparser                2.21
pydantic                 1.10.10
Pygments                 2.15.1
PyGObject                3.42.1
PyHamcrest               2.0.2
PyJWT                    2.3.0
PyMuPDF                  1.22.3
pyOpenSSL                21.0.0
pypandoc                 1.11
pyparsing                2.4.7
pyre-extensions          0.0.29
pyrsistent               0.19.3
pyserial                 3.5
pytest                   7.4.0
python-apt               2.4.0+ubuntu1
python-dateutil          2.8.2
python-debian            0.1.43ubuntu1
python-docx              0.8.11
python-dotenv            1.0.0
python-linux-procfs      0.6.3
python-magic             0.4.24
python-pptx              0.6.21
pytz                     2023.3
pytz-deprecation-shim    0.1.0.post0
pyudev                   0.22.0
PyYAML                   6.0
red-black-tree-mod       1.20
regex                    2023.6.3
requests                 2.30.0
rfc3986                  1.5.0
rich                     13.0.1
RTFDE                    0.0.2
safetensors              0.3.1
scikit-learn             1.3.0
scipy                    1.11.1
screen-resolution-extra  0.0.0
SecretStorage            3.3.1
sentence-transformers    2.2.2
sentencepiece            0.1.97
service-identity         18.1.0
setuptools               59.6.0
shortuuid                1.0.11
six                      1.16.0
sniffio                  1.3.0
sos                      4.4
soupsieve                2.4.1
SQLAlchemy               2.0.19
ssh-import-id            5.11
starlette                0.27.0
sympy                    1.12
systemd-python           234
tabulate                 0.9.0
tenacity                 8.2.2
threadpoolctl            3.1.0
tokenizers               0.13.3
tomli                    2.0.1
torch                    2.0.1
torchvision              0.15.2
tqdm                     4.65.0
transformers             4.30.0
triton                   2.0.0
Twisted                  22.1.0
typer                    0.7.0
typing_extensions        4.7.1
typing-inspect           0.9.0
tzdata                   2023.3
tzlocal                  4.2
ubuntu-advantage-tools   8001
ubuntu-drivers-common    0.0.0
ufw                      0.36.1
unattended-upgrades      0.1
unstructured             0.6.6
urllib3                  2.0.2
uvicorn                  0.22.0
uvloop                   0.17.0
wadllib                  1.3.6
watchfiles               0.19.0
websockets               11.0.3
wheel                    0.37.1
wrapt                    1.14.1
xformers                 0.0.20
xkit                     0.0.0
XlsxWriter               3.1.2
xxhash                   3.2.0
yarl                     1.9.2
zipp                     1.0.0
zope.interface           5.4.0
zstandard                0.21.0

### 运行日志或截图

Loading the embedding model...
No sentence-transformers model found with name /root/text2vec-large-chinese. Creating a new one with MEAN pooling.
[2023-07-20 16:44:17,426] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
loading LLM...
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:10<00:00,  3.63s/it]
请输入问题：你好
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1259: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1353: UserWarning: Using `max_length`'s default (1000) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
Traceback (most recent call last):
  File "/root/Chinese-LLaMA-Alpaca/scripts/langchain/langchain_qa.py", line 115, in <module>
    print(qa.run(query))
  File "/root/langchain/langchain/chains/base.py", line 440, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/root/langchain/langchain/chains/base.py", line 243, in __call__
    raise e
  File "/root/langchain/langchain/chains/base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/root/langchain/langchain/chains/retrieval_qa/base.py", line 133, in _call
    answer = self.combine_documents_chain.run(
  File "/root/langchain/langchain/chains/base.py", line 445, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/root/langchain/langchain/chains/base.py", line 243, in __call__
    raise e
  File "/root/langchain/langchain/chains/base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/root/langchain/langchain/chains/combine_documents/base.py", line 106, in _call
    output, extra_return_dict = self.combine_docs(
  File "/root/langchain/langchain/chains/combine_documents/refine.py", line 152, in combine_docs
    res = self.initial_llm_chain.predict(callbacks=callbacks, **inputs)
  File "/root/langchain/langchain/chains/llm.py", line 252, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/root/langchain/langchain/chains/base.py", line 243, in __call__
    raise e
  File "/root/langchain/langchain/chains/base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/root/langchain/langchain/chains/llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/root/langchain/langchain/chains/llm.py", line 102, in generate
    return self.llm.generate_prompt(
  File "/root/langchain/langchain/llms/base.py", line 186, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/root/langchain/langchain/llms/base.py", line 279, in generate
    output = self._generate_helper(
  File "/root/langchain/langchain/llms/base.py", line 223, in _generate_helper
    raise e
  File "/root/langchain/langchain/llms/base.py", line 210, in _generate_helper
    self._generate(
  File "/root/langchain/langchain/llms/base.py", line 602, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/root/langchain/langchain/llms/huggingface_pipeline.py", line 169, in _call
    response = self.pipeline(prompt)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/text_generation.py", line 201, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1120, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1127, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1026, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/text_generation.py", line 263, in _forward
    generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1522, in generate
    return self.greedy_search(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2339, in greedy_search
    outputs = self(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 194, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

**Comment by airaria** [comment]
你的环境里没有GPU吗？
https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/c34ecaaafc5a77af6d04e588b2378b16dac95244/scripts/langchain/langchain_qa.py#L57
改成 
```python
load_type = torch.float32
```

**Comment by ai499** [comment]
@airaria 改成load_type = torch.float32可以了  谢谢
