### ISSUE TITLE
Chinese Alpaca Plus 13B预训练时Embed层无法正常训练与合并

### ISSUE THREAD

**Issue by Phinease** [ymcui/Chinese-LLaMA-Alpaca#781]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

基于Chinese Alpaca Plus 13B继续预训练，在预训练时，使用DS Zero 3 + CPU Param Offload。当要求训练`"embed_tokens,lm_head"`时，训练在此处报错：
```
    model_vocab_size = model.get_output_embeddings().weight.size(0)
    if not (
       (model_vocab_size==32000 and len(tokenizer)==49953) or \
       (model_vocab_size==32000 and len(tokenizer)==32000) or \
       (model_vocab_size==49953 and len(tokenizer)==49953) or \
       (model_vocab_size==49954 and len(tokenizer)==49954)
    ):
        raise ValueError(
            f"The combination of base model (size: {model_vocab_size}) and tokenizer (size: {len(tokenizer)}) is not a valid configuration. Please check our project wiki for further information. \n"
            "Valid configurations (base model / tokenizer):\n"
            "- Continue pre-training original LLaMA: 32000 / 32000 \n"
            "- Pre-training Chinese LLaMA based on original LLaMA: 32000 / 49953 \n"
            "- Continue pre-training Chinese LLaMA: 49953 / 49953 \n"
            "- Continue pre-training Chinese Alpaca: 49954 / 49954 \n")
```
经检查确认，model.get_output_embeddings().weight.size(0)结果如下：
```
model.get_output_embeddings().weight.size(): torch.Size([0])
```
经过多轮调试发现，当模型加载参数中缺少`low_cpu_mem_usage=True`时，模型加载后embedding层就会出现这种情况，当加入该参数，情况正常：
```
model.get_output_embeddings().weight.size():torch.Size([49954, 5120])
```

并且，当强制跳过这个`raise ValueError`，确实可以训练，训练时也会显示一个合理的参数量，并且在Loss上的优化也是相对明显的，可以认为这些参数在事实上更新了（不确定）：
```
trainable params: 527175680 || all params: 13215360000 || trainable%: 3.989113274250569
```
但是，在合并模型时，会出现如下问题：
```
  File "merge_llama_with_chinese_lora.py", line 319, in <module>
    base_model_sd[original_k].copy_(lora_model_sd[k])
RuntimeError: The size of tensor a (5120) must match the size of tensor b (0) at non-singleton dimension 1
```
经过对比训练`"embed_tokens,lm_head"`和纯lora的最后adapter文件大小相比，大小一致（31M），表明`"embed_tokens,lm_head"`没有被保存下来。在使用如下代码查看Peft模型时也发现，一开始这两层就没有大小：
```
    model.state_dict = (
        lambda self, *_, **__: get_peft_model_state_dict(self, old_state_dict())
    ).__get__(model, type(model))

    print("以下为训练模型情况：")
    model_state = model.state_dict()
    for key in model_state:
        print(f"{key}: {model_state[key].size()}")
        
结果：
base_model.model.model.embed_tokens.weight: torch.Size([0])
base_model.model.lm_head.weight: torch.Size([0])
```

总之，由于`low_cpu_mem_usage=True`与Zero 3有冲突，Zero 2的话又会导致显存不足：
```
Traceback (most recent call last):
  File "run_clm_pt_with_peft.py", line 597, in <module>
    main()
  File "run_clm_pt_with_peft.py", line 483, in main
    model = LlamaForCausalLM.from_pretrained(
  File "/home/XXXX/miniconda3/envs/finetuning/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2227, in from_pretrained
    raise ValueError(
ValueError: DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`.
```
**不知道有什么解决方法吗？多谢指教。拜托拜托**
注：不训练`"embed_tokens,lm_head"`时，预训练与合并一切正常。

### 依赖情况（代码类问题务必提供）

```
pip list | grep -E 'transformers|peft|torch'
peft               0.3.0.dev0
torch              2.0.1+cu117
transformers       4.30.2
```

### 运行日志或截图

暂无

**Comment by Phinease** [comment]
@iMountTai 请问一下对于多卡训练同样适用吗？当前使用四张A100
