### ISSUE TITLE
gradient_checkpointing 参数有何影响？

### ISSUE THREAD

**Issue by Tramac** [ymcui/Chinese-LLaMA-Alpaca#784]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

```
bash  run_sft.sh
```
在 ft 和 sft 时，如果 `--gradient_checkpointing` 参数不设置为 False，均会报以下错误：

<img width="745" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/22740819/78c9a193-95ae-4126-ab4a-da785e51d1a0">

请问此报错的原因是什么，以及将 `--gradient_checkpointing` 设置为 False 会有何影响？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
│ /env/lib/python3.10/site-packages/torch/_tensor.py:488 in backward      │
│                                                                                                  │
│    485 │   │   │   │   create_graph=create_graph,                                                │
│    486 │   │   │   │   inputs=inputs,                                                            │
│    487 │   │   │   )                                                                             │
│ ❱  488 │   │   torch.autograd.backward(                                                          │
│    489 │   │   │   self, gradient, retain_graph, create_graph, inputs=inputs                     │
│    490 │   │   )                                                                                 │
│    491                                                                                           │
│                                                                                                  │
│ /env/lib/python3.10/site-packages/torch/autograd/__init__.py:197 in     │
│ backward                                                                                         │
│                                                                                                  │
│   194 │   # The reason we repeat same the comment below is that                                  │
│   195 │   # some Python versions print out the first line of a multi-line function               │
│   196 │   # calls in the traceback and some print out the last line                              │
│ ❱ 197 │   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the bac   │
│   198 │   │   tensors, grad_tensors_, retain_graph, create_graph, inputs,                        │
│   199 │   │   allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to ru   │
│   200                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
  0%|                                                                            | 0/6397 [00:02<?, ?it/s$
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 11760) of bi$
ary:/env/bin/python3
Traceback (most recent call last):
  File "/env/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch', 'console_scripts', 'torchrun')())
  File "/env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocess$
ng/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/env/lib/python3.10/site-packages/torch/distributed/run.py", line 762, i$
 main
    run(args)
  File "/env/lib/python3.10/site-packages/torch/distributed/run.py", line 753, i$
 run
    elastic_launch(
  File "/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", li$
e 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", li$
e 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
run_clm_sft_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-24_14:31:24
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 11760)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by iMountTai** [comment]
当前代码设置`gradient_checkpointing=True`可以减少显存占用，设置为False理论上可能会出现OOM。其他问题调试一下吧

**Comment by Oliver-whsun** [comment]
遇到了和楼主一样的问题。设定--gradient_checkpointing 为False之后可以训练，但是不确定会带来什么影响。

**Comment by PhilisterD** [comment]
部分保留（或者不保留）中间网络的feature_map，而是在反向传播的时候重新计算，用时间换空间的一种优化现存的方式方式。
[Training Deep Nets with Sublinear Memory Cost](https://arxiv.org/abs/1604.06174)
