### ISSUE TITLE
3090 cudamemory 不够用25GB显存

### ISSUE THREAD

**Issue by illumionous** [ymcui/Chinese-LLaMA-Alpaca#807]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-13B

### 操作系统

Linux

### 详细描述问题

```
r=3e-4
lora_rank=8
lora_alpha=16
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
#lora_trainable="q_proj,v_proj"
#modules_to_save="embed_tokens,lm_head"
modules_to_save=""
lora_dropout=0.05

pretrained_model=/home/wilsontam/pyllama_data/13B_hf
tokenizer_path=/home/wilsontam/pyllama_data/13B_hf

dataset_dir=data.instruct2/train
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=300
gradient_accumulation_steps=16 # 1 GPU, 32 batch per GPU = 128 batch for 1step update
output_dir=outs/13B_instruct_8-1
#peft_model=path/to/peft/model/dir
validation_file=data.instruct2/val/8-1_val.json
force_resize_embeddings=False
```
当我用这个脚本去精调指令时，发生memoryout，首先是词袋是The vocab size of the tokenizer must be 49954, but found49953，我修改代码定义为49953，然后又发生memory不够

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```
依赖完全依照教程

### 运行日志或截图

```
rainable params: 31293440 || all params: 13231006720 || trainable%: 0.23651594064038084
08/02/2023 12:34:08 - INFO - __main__ - model.modules_to_save: None
Traceback (most recent call last):
  File "/home/nlp/lama/Chinese-LLaMA-Alpaca/./scripts/training/run_clm_sft_with_peft.py", line 441, in <module>
    main()
  File "/home/nlp/lama/Chinese-LLaMA-Alpaca/./scripts/training/run_clm_sft_with_peft.py", line 397, in main
    trainer = Trainer(
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/transformers/trainer.py", line 499, in __init__
    self._move_model_to_device(model, args.device)
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/transformers/trainer.py", line 741, in _move_model_to_device
    model = model.to(device)
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 136.00 MiB (GPU 0; 23.70 GiB total capacity; 22.79 GiB already allocated; 130.00 MiB free; 22.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3411336) of binary: /home/nlp/.conda/envs/finetune/bin/python
Traceback (most recent call last):
  File "/home/nlp/.conda/envs/finetune/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nlp/.conda/envs/finetune/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./scripts/training/run_clm_sft_with_peft.py FAILED
```

**Comment by bigcash** [comment]
13B应该不止需要25G显存吧，用zero3训练吧
