### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: not a ZIP archive

### ISSUE THREAD

**Issue by bobqianic** [ymcui/Chinese-LLaMA-Alpaca#97]
```
D:\LLaMA>py -3.10 -m pip list
Package            Version
------------------ -----------
accelerate         0.18.0
certifi            2022.12.7
charset-normalizer 3.1.0
colorama           0.4.6
filelock           3.11.0
huggingface-hub    0.13.4
idna               3.4
Jinja2             3.1.2
MarkupSafe         2.1.2
mpmath             1.3.0
networkx           3.1
numpy              1.24.2
packaging          23.0
peft               0.2.0
pip                23.0.1
psutil             5.9.4
PyYAML             6.0
regex              2023.3.23
requests           2.28.2
sentencepiece      0.1.97
setuptools         65.5.0
sympy              1.11.1
tokenizers         0.13.3
torch              2.0.0
tqdm               4.65.0
transformers       4.28.0.dev0
typing_extensions  4.5.0
urllib3            1.26.15
```

```
D:\>py -3.10 D:\LLaMA\convert_llama_weights_to_hf.py --input_dir D:\LLaMA --model_size 7B --output_dir D:\LLaMA\HF
Fetching all parameters from the checkpoint at D:\LLaMA\7B.
Traceback (most recent call last):
  File "D:\LLaMA\convert_llama_weights_to_hf.py", line 269, in <module>
    main()
  File "D:\LLaMA\convert_llama_weights_to_hf.py", line 257, in main
    write_model(
  File "D:\LLaMA\convert_llama_weights_to_hf.py", line 99, in write_model
    loaded = torch.load(os.path.join(input_base_path, "consolidated.00.pth"), map_location="cpu")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: not a ZIP archive
```

**Comment by bobqianic** [comment]
I solved this issue. The model weights file was corrupted, causing this issue. Re-download solved it.
